// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

package order

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-grpc-ecommerce-be/pb/common"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequestProductItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequestProductItem) Reset()         { *m = CreateOrderRequestProductItem{} }
func (m *CreateOrderRequestProductItem) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequestProductItem) ProtoMessage()    {}
func (*CreateOrderRequestProductItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

func (m *CreateOrderRequestProductItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequestProductItem.Unmarshal(m, b)
}
func (m *CreateOrderRequestProductItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequestProductItem.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequestProductItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequestProductItem.Merge(m, src)
}
func (m *CreateOrderRequestProductItem) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequestProductItem.Size(m)
}
func (m *CreateOrderRequestProductItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequestProductItem.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequestProductItem proto.InternalMessageInfo

func (m *CreateOrderRequestProductItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrderRequestProductItem) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	FullName             string                           `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Address              string                           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          string                           `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Notes                string                           `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Products             []*CreateOrderRequestProductItem `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{1}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateOrderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateOrderRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateOrderRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *CreateOrderRequest) GetProducts() []*CreateOrderRequestProductItem {
	if m != nil {
		return m.Products
	}
	return nil
}

type CreateOrderResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{2}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// List Order Admin
type ListOrderAdminRequest struct {
	Pagination           *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListOrderAdminRequest) Reset()         { *m = ListOrderAdminRequest{} }
func (m *ListOrderAdminRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrderAdminRequest) ProtoMessage()    {}
func (*ListOrderAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{3}
}

func (m *ListOrderAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderAdminRequest.Unmarshal(m, b)
}
func (m *ListOrderAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderAdminRequest.Marshal(b, m, deterministic)
}
func (m *ListOrderAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderAdminRequest.Merge(m, src)
}
func (m *ListOrderAdminRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrderAdminRequest.Size(m)
}
func (m *ListOrderAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderAdminRequest proto.InternalMessageInfo

func (m *ListOrderAdminRequest) GetPagination() *common.PaginationRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListOrderAdminResponseItemProduct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int64    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderAdminResponseItemProduct) Reset()         { *m = ListOrderAdminResponseItemProduct{} }
func (m *ListOrderAdminResponseItemProduct) String() string { return proto.CompactTextString(m) }
func (*ListOrderAdminResponseItemProduct) ProtoMessage()    {}
func (*ListOrderAdminResponseItemProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{4}
}

func (m *ListOrderAdminResponseItemProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderAdminResponseItemProduct.Unmarshal(m, b)
}
func (m *ListOrderAdminResponseItemProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderAdminResponseItemProduct.Marshal(b, m, deterministic)
}
func (m *ListOrderAdminResponseItemProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderAdminResponseItemProduct.Merge(m, src)
}
func (m *ListOrderAdminResponseItemProduct) XXX_Size() int {
	return xxx_messageInfo_ListOrderAdminResponseItemProduct.Size(m)
}
func (m *ListOrderAdminResponseItemProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderAdminResponseItemProduct.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderAdminResponseItemProduct proto.InternalMessageInfo

func (m *ListOrderAdminResponseItemProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListOrderAdminResponseItemProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListOrderAdminResponseItemProduct) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListOrderAdminResponseItemProduct) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ListOrderAdminResponseItem struct {
	Id                   string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               string                               `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Customer             string                               `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	StatusCode           string                               `protobuf:"bytes,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Total                float64                              `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt            *timestamppb.Timestamp               `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Products             []*ListOrderAdminResponseItemProduct `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ListOrderAdminResponseItem) Reset()         { *m = ListOrderAdminResponseItem{} }
func (m *ListOrderAdminResponseItem) String() string { return proto.CompactTextString(m) }
func (*ListOrderAdminResponseItem) ProtoMessage()    {}
func (*ListOrderAdminResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{5}
}

func (m *ListOrderAdminResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderAdminResponseItem.Unmarshal(m, b)
}
func (m *ListOrderAdminResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderAdminResponseItem.Marshal(b, m, deterministic)
}
func (m *ListOrderAdminResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderAdminResponseItem.Merge(m, src)
}
func (m *ListOrderAdminResponseItem) XXX_Size() int {
	return xxx_messageInfo_ListOrderAdminResponseItem.Size(m)
}
func (m *ListOrderAdminResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderAdminResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderAdminResponseItem proto.InternalMessageInfo

func (m *ListOrderAdminResponseItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListOrderAdminResponseItem) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *ListOrderAdminResponseItem) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *ListOrderAdminResponseItem) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *ListOrderAdminResponseItem) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListOrderAdminResponseItem) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ListOrderAdminResponseItem) GetProducts() []*ListOrderAdminResponseItemProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

type ListOrderAdminResponse struct {
	Base                 *common.BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pagination           *common.PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items                []*ListOrderAdminResponseItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListOrderAdminResponse) Reset()         { *m = ListOrderAdminResponse{} }
func (m *ListOrderAdminResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrderAdminResponse) ProtoMessage()    {}
func (*ListOrderAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{6}
}

func (m *ListOrderAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderAdminResponse.Unmarshal(m, b)
}
func (m *ListOrderAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderAdminResponse.Marshal(b, m, deterministic)
}
func (m *ListOrderAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderAdminResponse.Merge(m, src)
}
func (m *ListOrderAdminResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrderAdminResponse.Size(m)
}
func (m *ListOrderAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderAdminResponse proto.InternalMessageInfo

func (m *ListOrderAdminResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListOrderAdminResponse) GetPagination() *common.PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListOrderAdminResponse) GetItems() []*ListOrderAdminResponseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// List Order
type ListOrderRequest struct {
	Pagination           *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListOrderRequest) Reset()         { *m = ListOrderRequest{} }
func (m *ListOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrderRequest) ProtoMessage()    {}
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{7}
}

func (m *ListOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderRequest.Unmarshal(m, b)
}
func (m *ListOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderRequest.Marshal(b, m, deterministic)
}
func (m *ListOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderRequest.Merge(m, src)
}
func (m *ListOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrderRequest.Size(m)
}
func (m *ListOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderRequest proto.InternalMessageInfo

func (m *ListOrderRequest) GetPagination() *common.PaginationRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListOrderResponseItemProduct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int64    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderResponseItemProduct) Reset()         { *m = ListOrderResponseItemProduct{} }
func (m *ListOrderResponseItemProduct) String() string { return proto.CompactTextString(m) }
func (*ListOrderResponseItemProduct) ProtoMessage()    {}
func (*ListOrderResponseItemProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{8}
}

func (m *ListOrderResponseItemProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderResponseItemProduct.Unmarshal(m, b)
}
func (m *ListOrderResponseItemProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderResponseItemProduct.Marshal(b, m, deterministic)
}
func (m *ListOrderResponseItemProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderResponseItemProduct.Merge(m, src)
}
func (m *ListOrderResponseItemProduct) XXX_Size() int {
	return xxx_messageInfo_ListOrderResponseItemProduct.Size(m)
}
func (m *ListOrderResponseItemProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderResponseItemProduct.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderResponseItemProduct proto.InternalMessageInfo

func (m *ListOrderResponseItemProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListOrderResponseItemProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListOrderResponseItemProduct) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListOrderResponseItemProduct) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ListOrderResponseItem struct {
	Id                   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               string                          `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Customer             string                          `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	StatusCode           string                          `protobuf:"bytes,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Total                float64                         `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt            *timestamppb.Timestamp          `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Products             []*ListOrderResponseItemProduct `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	XenditInvoiceUrl     string                          `protobuf:"bytes,8,opt,name=xendit_invoice_url,json=xenditInvoiceUrl,proto3" json:"xendit_invoice_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ListOrderResponseItem) Reset()         { *m = ListOrderResponseItem{} }
func (m *ListOrderResponseItem) String() string { return proto.CompactTextString(m) }
func (*ListOrderResponseItem) ProtoMessage()    {}
func (*ListOrderResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{9}
}

func (m *ListOrderResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderResponseItem.Unmarshal(m, b)
}
func (m *ListOrderResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderResponseItem.Marshal(b, m, deterministic)
}
func (m *ListOrderResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderResponseItem.Merge(m, src)
}
func (m *ListOrderResponseItem) XXX_Size() int {
	return xxx_messageInfo_ListOrderResponseItem.Size(m)
}
func (m *ListOrderResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderResponseItem proto.InternalMessageInfo

func (m *ListOrderResponseItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListOrderResponseItem) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *ListOrderResponseItem) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *ListOrderResponseItem) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *ListOrderResponseItem) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListOrderResponseItem) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ListOrderResponseItem) GetProducts() []*ListOrderResponseItemProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *ListOrderResponseItem) GetXenditInvoiceUrl() string {
	if m != nil {
		return m.XenditInvoiceUrl
	}
	return ""
}

type ListOrderResponse struct {
	Base                 *common.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pagination           *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Items                []*ListOrderResponseItem   `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListOrderResponse) Reset()         { *m = ListOrderResponse{} }
func (m *ListOrderResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrderResponse) ProtoMessage()    {}
func (*ListOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{10}
}

func (m *ListOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderResponse.Unmarshal(m, b)
}
func (m *ListOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderResponse.Marshal(b, m, deterministic)
}
func (m *ListOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderResponse.Merge(m, src)
}
func (m *ListOrderResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrderResponse.Size(m)
}
func (m *ListOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderResponse proto.InternalMessageInfo

func (m *ListOrderResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListOrderResponse) GetPagination() *common.PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListOrderResponse) GetItems() []*ListOrderResponseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type DetailOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailOrderRequest) Reset()         { *m = DetailOrderRequest{} }
func (m *DetailOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DetailOrderRequest) ProtoMessage()    {}
func (*DetailOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{11}
}

func (m *DetailOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailOrderRequest.Unmarshal(m, b)
}
func (m *DetailOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailOrderRequest.Marshal(b, m, deterministic)
}
func (m *DetailOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailOrderRequest.Merge(m, src)
}
func (m *DetailOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DetailOrderRequest.Size(m)
}
func (m *DetailOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailOrderRequest proto.InternalMessageInfo

func (m *DetailOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailOrderResponseItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int64    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailOrderResponseItem) Reset()         { *m = DetailOrderResponseItem{} }
func (m *DetailOrderResponseItem) String() string { return proto.CompactTextString(m) }
func (*DetailOrderResponseItem) ProtoMessage()    {}
func (*DetailOrderResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{12}
}

func (m *DetailOrderResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailOrderResponseItem.Unmarshal(m, b)
}
func (m *DetailOrderResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailOrderResponseItem.Marshal(b, m, deterministic)
}
func (m *DetailOrderResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailOrderResponseItem.Merge(m, src)
}
func (m *DetailOrderResponseItem) XXX_Size() int {
	return xxx_messageInfo_DetailOrderResponseItem.Size(m)
}
func (m *DetailOrderResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailOrderResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_DetailOrderResponseItem proto.InternalMessageInfo

func (m *DetailOrderResponseItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetailOrderResponseItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetailOrderResponseItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DetailOrderResponseItem) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type DetailOrderResponse struct {
	Base                 *common.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id                   string                     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Number               string                     `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	UserFullName         string                     `protobuf:"bytes,4,opt,name=user_full_name,json=userFullName,proto3" json:"user_full_name,omitempty"`
	Address              string                     `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          string                     `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Notes                string                     `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	OrderStatusCode      string                     `protobuf:"bytes,8,opt,name=order_status_code,json=orderStatusCode,proto3" json:"order_status_code,omitempty"`
	CreatedAt            *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XenditInvoiceUrl     string                     `protobuf:"bytes,10,opt,name=xendit_invoice_url,json=xenditInvoiceUrl,proto3" json:"xendit_invoice_url,omitempty"`
	Items                []*DetailOrderResponseItem `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	Total                float64                    `protobuf:"fixed64,12,opt,name=total,proto3" json:"total,omitempty"`
	ExpiredAt            *timestamppb.Timestamp     `protobuf:"bytes,13,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DetailOrderResponse) Reset()         { *m = DetailOrderResponse{} }
func (m *DetailOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DetailOrderResponse) ProtoMessage()    {}
func (*DetailOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{13}
}

func (m *DetailOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailOrderResponse.Unmarshal(m, b)
}
func (m *DetailOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailOrderResponse.Marshal(b, m, deterministic)
}
func (m *DetailOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailOrderResponse.Merge(m, src)
}
func (m *DetailOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DetailOrderResponse.Size(m)
}
func (m *DetailOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailOrderResponse proto.InternalMessageInfo

func (m *DetailOrderResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DetailOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetailOrderResponse) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *DetailOrderResponse) GetUserFullName() string {
	if m != nil {
		return m.UserFullName
	}
	return ""
}

func (m *DetailOrderResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DetailOrderResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *DetailOrderResponse) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *DetailOrderResponse) GetOrderStatusCode() string {
	if m != nil {
		return m.OrderStatusCode
	}
	return ""
}

func (m *DetailOrderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DetailOrderResponse) GetXenditInvoiceUrl() string {
	if m != nil {
		return m.XenditInvoiceUrl
	}
	return ""
}

func (m *DetailOrderResponse) GetItems() []*DetailOrderResponseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *DetailOrderResponse) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DetailOrderResponse) GetExpiredAt() *timestamppb.Timestamp {
	if m != nil {
		return m.ExpiredAt
	}
	return nil
}

type UpdateOrderStatusRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatusCode        string   `protobuf:"bytes,2,opt,name=new_status_code,json=newStatusCode,proto3" json:"new_status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderStatusRequest) Reset()         { *m = UpdateOrderStatusRequest{} }
func (m *UpdateOrderStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderStatusRequest) ProtoMessage()    {}
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{14}
}

func (m *UpdateOrderStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderStatusRequest.Unmarshal(m, b)
}
func (m *UpdateOrderStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderStatusRequest.Merge(m, src)
}
func (m *UpdateOrderStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderStatusRequest.Size(m)
}
func (m *UpdateOrderStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderStatusRequest proto.InternalMessageInfo

func (m *UpdateOrderStatusRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *UpdateOrderStatusRequest) GetNewStatusCode() string {
	if m != nil {
		return m.NewStatusCode
	}
	return ""
}

type UpdateOrderStatusResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateOrderStatusResponse) Reset()         { *m = UpdateOrderStatusResponse{} }
func (m *UpdateOrderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderStatusResponse) ProtoMessage()    {}
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{15}
}

func (m *UpdateOrderStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderStatusResponse.Unmarshal(m, b)
}
func (m *UpdateOrderStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderStatusResponse.Marshal(b, m, deterministic)
}
func (m *UpdateOrderStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderStatusResponse.Merge(m, src)
}
func (m *UpdateOrderStatusResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderStatusResponse.Size(m)
}
func (m *UpdateOrderStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderStatusResponse proto.InternalMessageInfo

func (m *UpdateOrderStatusResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateOrderRequestProductItem)(nil), "order.CreateOrderRequestProductItem")
	proto.RegisterType((*CreateOrderRequest)(nil), "order.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "order.CreateOrderResponse")
	proto.RegisterType((*ListOrderAdminRequest)(nil), "order.ListOrderAdminRequest")
	proto.RegisterType((*ListOrderAdminResponseItemProduct)(nil), "order.ListOrderAdminResponseItemProduct")
	proto.RegisterType((*ListOrderAdminResponseItem)(nil), "order.ListOrderAdminResponseItem")
	proto.RegisterType((*ListOrderAdminResponse)(nil), "order.ListOrderAdminResponse")
	proto.RegisterType((*ListOrderRequest)(nil), "order.ListOrderRequest")
	proto.RegisterType((*ListOrderResponseItemProduct)(nil), "order.ListOrderResponseItemProduct")
	proto.RegisterType((*ListOrderResponseItem)(nil), "order.ListOrderResponseItem")
	proto.RegisterType((*ListOrderResponse)(nil), "order.ListOrderResponse")
	proto.RegisterType((*DetailOrderRequest)(nil), "order.DetailOrderRequest")
	proto.RegisterType((*DetailOrderResponseItem)(nil), "order.DetailOrderResponseItem")
	proto.RegisterType((*DetailOrderResponse)(nil), "order.DetailOrderResponse")
	proto.RegisterType((*UpdateOrderStatusRequest)(nil), "order.UpdateOrderStatusRequest")
	proto.RegisterType((*UpdateOrderStatusResponse)(nil), "order.UpdateOrderStatusResponse")
}

func init() { proto.RegisterFile("order/order.proto", fileDescriptor_fa47a2077d8980ed) }

var fileDescriptor_fa47a2077d8980ed = []byte{
	// 960 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x97, 0xdf, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0xe5, 0xa4, 0x6e, 0x92, 0x49, 0xaf, 0xd7, 0xee, 0x95, 0xab, 0x6b, 0xda, 0x6b, 0x6b,
	0x8a, 0x88, 0x10, 0x4d, 0x50, 0x40, 0x42, 0xf0, 0x00, 0xb4, 0x57, 0xd0, 0x55, 0x70, 0x3f, 0x64,
	0x38, 0x1e, 0x78, 0xb1, 0x1c, 0x7b, 0x2e, 0x58, 0x8a, 0xbd, 0xbe, 0xf5, 0xba, 0x77, 0xf7, 0xc8,
	0x7f, 0xc1, 0x3f, 0xc1, 0x33, 0xd2, 0x89, 0x3f, 0x8b, 0x47, 0x24, 0x90, 0x77, 0xd7, 0x8e, 0x1d,
	0x3b, 0xa9, 0x8a, 0x4e, 0xf7, 0xc0, 0x4b, 0x95, 0xf5, 0x7c, 0x3d, 0xbb, 0x33, 0xf3, 0x19, 0xcf,
	0x16, 0xb6, 0x29, 0xf3, 0x91, 0x8d, 0xc4, 0xdf, 0x61, 0xcc, 0x28, 0xa7, 0x44, 0x17, 0x0b, 0xf3,
	0xdd, 0x49, 0xfa, 0x6c, 0x74, 0xe5, 0xce, 0x02, 0xdf, 0xe5, 0x58, 0xfc, 0x90, 0x1a, 0xd3, 0xf4,
	0x68, 0x18, 0xd2, 0x68, 0x34, 0x71, 0x13, 0x74, 0x18, 0x26, 0x31, 0x8d, 0x92, 0xdc, 0xb6, 0xab,
	0x6c, 0xb1, 0x3b, 0x0d, 0x22, 0x97, 0x07, 0x34, 0x52, 0x86, 0xc3, 0x29, 0xa5, 0xd3, 0x19, 0x8e,
	0xc4, 0x2a, 0xf3, 0xce, 0x83, 0x10, 0x13, 0xee, 0x86, 0xb1, 0x14, 0x58, 0xdf, 0xc1, 0xc1, 0x7d,
	0x86, 0x2e, 0xc7, 0xc7, 0xd9, 0x09, 0x6c, 0x7c, 0x9e, 0x62, 0xc2, 0x9f, 0x30, 0xea, 0xa7, 0x1e,
	0xbf, 0xe4, 0x18, 0x92, 0x4d, 0x68, 0x05, 0xbe, 0xa1, 0x1d, 0x69, 0x83, 0x9e, 0xdd, 0x0a, 0x7c,
	0x62, 0x42, 0xf7, 0x79, 0xea, 0x46, 0x3c, 0xe0, 0xaf, 0x8c, 0xd6, 0x91, 0x36, 0x68, 0xdb, 0xc5,
	0xda, 0xfa, 0x4b, 0x03, 0x52, 0xf7, 0x46, 0x3e, 0x80, 0xde, 0xb3, 0x74, 0x36, 0x73, 0x22, 0x37,
	0x44, 0xe9, 0xe9, 0x1c, 0x5e, 0x3f, 0xe8, 0x30, 0x7d, 0x4b, 0x33, 0xfe, 0xd1, 0xec, 0x6e, 0x66,
	0x7c, 0xe4, 0x86, 0x48, 0x4e, 0xa0, 0xe3, 0xfa, 0x3e, 0xc3, 0x24, 0x11, 0xae, 0xab, 0xb2, 0xdc,
	0x44, 0x4e, 0x61, 0x23, 0xfe, 0x85, 0x46, 0xe8, 0x44, 0x69, 0x38, 0x41, 0x66, 0xb4, 0x6b, 0xd2,
	0xbe, 0xb0, 0x3f, 0x12, 0x66, 0x72, 0x0f, 0xf4, 0x88, 0x72, 0x4c, 0x8c, 0x35, 0xa1, 0xeb, 0xbe,
	0x7e, 0xa0, 0xb3, 0x76, 0xa6, 0x92, 0x8f, 0xc9, 0xd7, 0xd0, 0x8d, 0x65, 0xbc, 0x89, 0xa1, 0x1f,
	0xb5, 0x07, 0xfd, 0xf1, 0xc9, 0x50, 0xd6, 0x66, 0x65, 0x62, 0xec, 0xe2, 0x2d, 0xeb, 0x31, 0xdc,
	0xa9, 0x48, 0x65, 0x69, 0xc8, 0x00, 0xd6, 0xb2, 0x5a, 0x89, 0x88, 0xfb, 0xe3, 0x9d, 0xa1, 0xac,
	0xd1, 0xf0, 0xdc, 0x4d, 0x30, 0xd7, 0xd8, 0x42, 0xa1, 0x72, 0xdc, 0xca, 0x73, 0x6c, 0xd9, 0xf0,
	0xce, 0xf7, 0x41, 0xc2, 0x85, 0xbb, 0x33, 0x3f, 0x0c, 0xa2, 0x3c, 0x93, 0x9f, 0x03, 0xcc, 0x4b,
	0xac, 0x1c, 0xef, 0xe5, 0x8e, 0x9f, 0x14, 0x16, 0x25, 0xb7, 0x4b, 0x62, 0xeb, 0x15, 0x1c, 0x2f,
	0xfa, 0x94, 0x67, 0xc8, 0x82, 0x51, 0x71, 0xd5, 0x8a, 0x4d, 0x60, 0x4d, 0x14, 0x4d, 0x1e, 0x4d,
	0xfc, 0x26, 0x3b, 0xa0, 0xc7, 0x2c, 0xf0, 0x50, 0xe4, 0x5d, 0xb3, 0xe5, 0xa2, 0x82, 0xc5, 0xda,
	0x02, 0x16, 0xbf, 0xb5, 0xc0, 0x5c, 0xbe, 0x77, 0x6d, 0xd3, 0xbb, 0xb0, 0xae, 0x2a, 0x2b, 0xb7,
	0x55, 0xab, 0x6c, 0x0b, 0x2f, 0x4d, 0x38, 0x0d, 0xf3, 0x9a, 0xdb, 0xc5, 0x9a, 0x1c, 0x42, 0x3f,
	0xe1, 0x2e, 0x4f, 0x13, 0xc7, 0xa3, 0x3e, 0xca, 0x52, 0xdb, 0x20, 0x1f, 0xdd, 0xa7, 0xbe, 0x38,
	0x35, 0xa7, 0xdc, 0x9d, 0x19, 0xba, 0x3c, 0xb5, 0x58, 0x64, 0xf9, 0xf4, 0x44, 0xe5, 0x7c, 0xc7,
	0xe5, 0xc6, 0xba, 0xc8, 0xa7, 0x39, 0x94, 0x3d, 0x33, 0xcc, 0x7b, 0x66, 0xf8, 0x63, 0xde, 0x33,
	0x76, 0x4f, 0xa9, 0xcf, 0x38, 0xb9, 0x28, 0x61, 0xd3, 0x11, 0xd8, 0x0c, 0x14, 0x36, 0xd7, 0xa6,
	0xb9, 0x84, 0xce, 0x1f, 0x1a, 0xdc, 0x6d, 0xd6, 0xdf, 0x00, 0x9f, 0x2f, 0x2a, 0x54, 0xb4, 0x54,
	0x14, 0x0d, 0x54, 0xa8, 0xb7, 0x4a, 0x6a, 0xf2, 0x19, 0xe8, 0x01, 0xc7, 0x30, 0x31, 0xda, 0x22,
	0x86, 0xe3, 0x6b, 0x63, 0xb0, 0xa5, 0xde, 0x7a, 0x08, 0x5b, 0x85, 0xe8, 0x0d, 0xe0, 0xc9, 0x61,
	0xbf, 0xe4, 0xee, 0x6d, 0x91, 0xf9, 0x67, 0xab, 0xd4, 0x69, 0xff, 0x03, 0x28, 0xbf, 0xaa, 0x41,
	0xf9, 0xde, 0x62, 0x41, 0x57, 0xf2, 0x48, 0x3e, 0x02, 0xf2, 0x12, 0x23, 0x3f, 0xe0, 0x4e, 0x10,
	0x5d, 0xd1, 0xc0, 0x43, 0x27, 0x65, 0x33, 0xa3, 0x2b, 0x4e, 0xbe, 0x25, 0x2d, 0x97, 0xd2, 0xf0,
	0x94, 0xcd, 0xac, 0xdf, 0x35, 0xd8, 0xae, 0x39, 0x7e, 0x4b, 0xe0, 0x8e, 0xab, 0xe0, 0xee, 0xaf,
	0x8a, 0x33, 0x67, 0xf6, 0x63, 0x20, 0x17, 0xc8, 0xdd, 0x60, 0x56, 0xa1, 0xd6, 0x9c, 0x97, 0xba,
	0x32, 0x45, 0xb2, 0x2f, 0x31, 0x85, 0xdd, 0xca, 0x1b, 0x2b, 0x08, 0x79, 0x33, 0x44, 0xfe, 0xdd,
	0x86, 0x3b, 0x0d, 0x3b, 0xfe, 0xf7, 0x61, 0x52, 0x22, 0xb7, 0x5d, 0x21, 0xf7, 0x04, 0x36, 0xd3,
	0x04, 0x99, 0x33, 0x1f, 0xcd, 0x12, 0xd0, 0x8d, 0xec, 0xe9, 0xb7, 0xf9, 0x48, 0x36, 0xe6, 0x23,
	0x59, 0x17, 0xe6, 0x62, 0x0c, 0x1f, 0x2f, 0x8c, 0xe1, 0x75, 0x61, 0xae, 0x8c, 0xde, 0x9d, 0x7c,
	0xf4, 0x76, 0x84, 0x4d, 0x0d, 0xdc, 0x0f, 0xd5, 0x0d, 0xc8, 0x29, 0x37, 0x87, 0x44, 0xec, 0xb6,
	0x30, 0xfc, 0x30, 0xef, 0x90, 0x6a, 0x2f, 0xf4, 0x6e, 0xd2, 0x0b, 0xcd, 0x28, 0x43, 0x33, 0xca,
	0xe4, 0xd3, 0x1c, 0xa7, 0xbe, 0xc0, 0xe9, 0x9e, 0xc2, 0x69, 0x49, 0xf1, 0x15, 0x50, 0xf3, 0x06,
	0xde, 0x58, 0x68, 0x60, 0x7c, 0x19, 0x07, 0x4c, 0x1e, 0xfa, 0xd6, 0xf5, 0x87, 0x56, 0xea, 0x33,
	0x6e, 0xa5, 0x60, 0x3c, 0x8d, 0xfd, 0xfc, 0x2a, 0x21, 0x13, 0x91, 0x73, 0xfa, 0x3e, 0x74, 0x65,
	0xde, 0x1a, 0x69, 0xed, 0x08, 0xdb, 0xa5, 0x4f, 0xc6, 0x70, 0x3b, 0xc2, 0x17, 0x95, 0xe4, 0xd6,
	0x2f, 0x53, 0xb7, 0x22, 0x7c, 0x31, 0x4f, 0xb3, 0xf5, 0x0d, 0xec, 0x35, 0x6c, 0x7b, 0x53, 0xf4,
	0xc6, 0xbf, 0xb6, 0x61, 0x43, 0x7a, 0x40, 0x76, 0x95, 0x91, 0x7e, 0x01, 0xfd, 0xd2, 0xcd, 0x88,
	0xec, 0x2d, 0xbd, 0x58, 0x99, 0x66, 0x93, 0x49, 0x1d, 0xe0, 0x21, 0x6c, 0x56, 0xe7, 0x11, 0xd9,
	0x5f, 0x32, 0xa6, 0xa4, 0xaf, 0x83, 0x95, 0x43, 0x8c, 0x7c, 0x09, 0xbd, 0xc2, 0x42, 0x76, 0xeb,
	0xdf, 0x0d, 0xe9, 0xc4, 0x58, 0xf6, 0x41, 0xc9, 0x82, 0x2a, 0x61, 0x51, 0x04, 0x55, 0xff, 0xb2,
	0x14, 0x41, 0x35, 0x35, 0xf4, 0x4f, 0xb0, 0x5d, 0x4b, 0x39, 0x39, 0x54, 0x2f, 0x2c, 0x63, 0xc0,
	0x3c, 0x5a, 0x2e, 0x90, 0x7e, 0xcf, 0x0f, 0x7f, 0x3e, 0x98, 0xd2, 0xd3, 0x29, 0x8b, 0xbd, 0x53,
	0xcc, 0x2a, 0x85, 0xcc, 0xc3, 0xd3, 0x09, 0x8e, 0xe2, 0x89, 0xfc, 0x8f, 0x63, 0xb2, 0x2e, 0x08,
	0xfc, 0xe4, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x40, 0x58, 0x60, 0x87, 0x0c, 0x00, 0x00,
}
