// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product/product.proto

package product

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-grpc-ecommerce-be/pb/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageFileName        string   `protobuf:"bytes,4,opt,name=image_file_name,json=imageFileName,proto3" json:"image_file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{0}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProductRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateProductRequest) GetImageFileName() string {
	if m != nil {
		return m.ImageFileName
	}
	return ""
}

type CreateProductResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{1}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailProductRequest) Reset()         { *m = DetailProductRequest{} }
func (m *DetailProductRequest) String() string { return proto.CompactTextString(m) }
func (*DetailProductRequest) ProtoMessage()    {}
func (*DetailProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{2}
}

func (m *DetailProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailProductRequest.Unmarshal(m, b)
}
func (m *DetailProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailProductRequest.Marshal(b, m, deterministic)
}
func (m *DetailProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailProductRequest.Merge(m, src)
}
func (m *DetailProductRequest) XXX_Size() int {
	return xxx_messageInfo_DetailProductRequest.Size(m)
}
func (m *DetailProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailProductRequest proto.InternalMessageInfo

func (m *DetailProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailProductResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64              `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl             string               `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DetailProductResponse) Reset()         { *m = DetailProductResponse{} }
func (m *DetailProductResponse) String() string { return proto.CompactTextString(m) }
func (*DetailProductResponse) ProtoMessage()    {}
func (*DetailProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{3}
}

func (m *DetailProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailProductResponse.Unmarshal(m, b)
}
func (m *DetailProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailProductResponse.Marshal(b, m, deterministic)
}
func (m *DetailProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailProductResponse.Merge(m, src)
}
func (m *DetailProductResponse) XXX_Size() int {
	return xxx_messageInfo_DetailProductResponse.Size(m)
}
func (m *DetailProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailProductResponse proto.InternalMessageInfo

func (m *DetailProductResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DetailProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetailProductResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetailProductResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DetailProductResponse) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DetailProductResponse) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type EditProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageFileName        string   `protobuf:"bytes,5,opt,name=image_file_name,json=imageFileName,proto3" json:"image_file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProductRequest) Reset()         { *m = EditProductRequest{} }
func (m *EditProductRequest) String() string { return proto.CompactTextString(m) }
func (*EditProductRequest) ProtoMessage()    {}
func (*EditProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{4}
}

func (m *EditProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProductRequest.Unmarshal(m, b)
}
func (m *EditProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProductRequest.Marshal(b, m, deterministic)
}
func (m *EditProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProductRequest.Merge(m, src)
}
func (m *EditProductRequest) XXX_Size() int {
	return xxx_messageInfo_EditProductRequest.Size(m)
}
func (m *EditProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditProductRequest proto.InternalMessageInfo

func (m *EditProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditProductRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *EditProductRequest) GetImageFileName() string {
	if m != nil {
		return m.ImageFileName
	}
	return ""
}

type EditProductResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EditProductResponse) Reset()         { *m = EditProductResponse{} }
func (m *EditProductResponse) String() string { return proto.CompactTextString(m) }
func (*EditProductResponse) ProtoMessage()    {}
func (*EditProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{5}
}

func (m *EditProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProductResponse.Unmarshal(m, b)
}
func (m *EditProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProductResponse.Marshal(b, m, deterministic)
}
func (m *EditProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProductResponse.Merge(m, src)
}
func (m *EditProductResponse) XXX_Size() int {
	return xxx_messageInfo_EditProductResponse.Size(m)
}
func (m *EditProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditProductResponse proto.InternalMessageInfo

func (m *EditProductResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *EditProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{6}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProductResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteProductResponse) Reset()         { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()    {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{7}
}

func (m *DeleteProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductResponse.Unmarshal(m, b)
}
func (m *DeleteProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductResponse.Merge(m, src)
}
func (m *DeleteProductResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductResponse.Size(m)
}
func (m *DeleteProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductResponse proto.InternalMessageInfo

func (m *DeleteProductResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type ListProductRequest struct {
	Pagination           *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListProductRequest) Reset()         { *m = ListProductRequest{} }
func (m *ListProductRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductRequest) ProtoMessage()    {}
func (*ListProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{8}
}

func (m *ListProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductRequest.Unmarshal(m, b)
}
func (m *ListProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductRequest.Marshal(b, m, deterministic)
}
func (m *ListProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductRequest.Merge(m, src)
}
func (m *ListProductRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductRequest.Size(m)
}
func (m *ListProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductRequest proto.InternalMessageInfo

func (m *ListProductRequest) GetPagination() *common.PaginationRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListProductResponseItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductResponseItem) Reset()         { *m = ListProductResponseItem{} }
func (m *ListProductResponseItem) String() string { return proto.CompactTextString(m) }
func (*ListProductResponseItem) ProtoMessage()    {}
func (*ListProductResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{9}
}

func (m *ListProductResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductResponseItem.Unmarshal(m, b)
}
func (m *ListProductResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductResponseItem.Marshal(b, m, deterministic)
}
func (m *ListProductResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductResponseItem.Merge(m, src)
}
func (m *ListProductResponseItem) XXX_Size() int {
	return xxx_messageInfo_ListProductResponseItem.Size(m)
}
func (m *ListProductResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductResponseItem proto.InternalMessageInfo

func (m *ListProductResponseItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListProductResponseItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListProductResponseItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ListProductResponseItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListProductResponseItem) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type ListProductResponse struct {
	Base                 *common.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pagination           *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data                 []*ListProductResponseItem `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListProductResponse) Reset()         { *m = ListProductResponse{} }
func (m *ListProductResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductResponse) ProtoMessage()    {}
func (*ListProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{10}
}

func (m *ListProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductResponse.Unmarshal(m, b)
}
func (m *ListProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductResponse.Marshal(b, m, deterministic)
}
func (m *ListProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductResponse.Merge(m, src)
}
func (m *ListProductResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductResponse.Size(m)
}
func (m *ListProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductResponse proto.InternalMessageInfo

func (m *ListProductResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListProductResponse) GetPagination() *common.PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListProductResponse) GetData() []*ListProductResponseItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListProductAdminRequest struct {
	Pagination           *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListProductAdminRequest) Reset()         { *m = ListProductAdminRequest{} }
func (m *ListProductAdminRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductAdminRequest) ProtoMessage()    {}
func (*ListProductAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{11}
}

func (m *ListProductAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductAdminRequest.Unmarshal(m, b)
}
func (m *ListProductAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductAdminRequest.Marshal(b, m, deterministic)
}
func (m *ListProductAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductAdminRequest.Merge(m, src)
}
func (m *ListProductAdminRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductAdminRequest.Size(m)
}
func (m *ListProductAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductAdminRequest proto.InternalMessageInfo

func (m *ListProductAdminRequest) GetPagination() *common.PaginationRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ListProductAdminResponseItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductAdminResponseItem) Reset()         { *m = ListProductAdminResponseItem{} }
func (m *ListProductAdminResponseItem) String() string { return proto.CompactTextString(m) }
func (*ListProductAdminResponseItem) ProtoMessage()    {}
func (*ListProductAdminResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{12}
}

func (m *ListProductAdminResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductAdminResponseItem.Unmarshal(m, b)
}
func (m *ListProductAdminResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductAdminResponseItem.Marshal(b, m, deterministic)
}
func (m *ListProductAdminResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductAdminResponseItem.Merge(m, src)
}
func (m *ListProductAdminResponseItem) XXX_Size() int {
	return xxx_messageInfo_ListProductAdminResponseItem.Size(m)
}
func (m *ListProductAdminResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductAdminResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductAdminResponseItem proto.InternalMessageInfo

func (m *ListProductAdminResponseItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListProductAdminResponseItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListProductAdminResponseItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ListProductAdminResponseItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListProductAdminResponseItem) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type ListProductAdminResponse struct {
	Base                 *common.BaseResponse            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pagination           *common.PaginationResponse      `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data                 []*ListProductAdminResponseItem `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ListProductAdminResponse) Reset()         { *m = ListProductAdminResponse{} }
func (m *ListProductAdminResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductAdminResponse) ProtoMessage()    {}
func (*ListProductAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{13}
}

func (m *ListProductAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductAdminResponse.Unmarshal(m, b)
}
func (m *ListProductAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductAdminResponse.Marshal(b, m, deterministic)
}
func (m *ListProductAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductAdminResponse.Merge(m, src)
}
func (m *ListProductAdminResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductAdminResponse.Size(m)
}
func (m *ListProductAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductAdminResponse proto.InternalMessageInfo

func (m *ListProductAdminResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListProductAdminResponse) GetPagination() *common.PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListProductAdminResponse) GetData() []*ListProductAdminResponseItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type HighlightProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HighlightProductsRequest) Reset()         { *m = HighlightProductsRequest{} }
func (m *HighlightProductsRequest) String() string { return proto.CompactTextString(m) }
func (*HighlightProductsRequest) ProtoMessage()    {}
func (*HighlightProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{14}
}

func (m *HighlightProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HighlightProductsRequest.Unmarshal(m, b)
}
func (m *HighlightProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HighlightProductsRequest.Marshal(b, m, deterministic)
}
func (m *HighlightProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighlightProductsRequest.Merge(m, src)
}
func (m *HighlightProductsRequest) XXX_Size() int {
	return xxx_messageInfo_HighlightProductsRequest.Size(m)
}
func (m *HighlightProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HighlightProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HighlightProductsRequest proto.InternalMessageInfo

type HighlightProductsResponseItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HighlightProductsResponseItem) Reset()         { *m = HighlightProductsResponseItem{} }
func (m *HighlightProductsResponseItem) String() string { return proto.CompactTextString(m) }
func (*HighlightProductsResponseItem) ProtoMessage()    {}
func (*HighlightProductsResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{15}
}

func (m *HighlightProductsResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HighlightProductsResponseItem.Unmarshal(m, b)
}
func (m *HighlightProductsResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HighlightProductsResponseItem.Marshal(b, m, deterministic)
}
func (m *HighlightProductsResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighlightProductsResponseItem.Merge(m, src)
}
func (m *HighlightProductsResponseItem) XXX_Size() int {
	return xxx_messageInfo_HighlightProductsResponseItem.Size(m)
}
func (m *HighlightProductsResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_HighlightProductsResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_HighlightProductsResponseItem proto.InternalMessageInfo

func (m *HighlightProductsResponseItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HighlightProductsResponseItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HighlightProductsResponseItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *HighlightProductsResponseItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *HighlightProductsResponseItem) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type HighlightProductsResponse struct {
	Base                 *common.BaseResponse             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data                 []*HighlightProductsResponseItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *HighlightProductsResponse) Reset()         { *m = HighlightProductsResponse{} }
func (m *HighlightProductsResponse) String() string { return proto.CompactTextString(m) }
func (*HighlightProductsResponse) ProtoMessage()    {}
func (*HighlightProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{16}
}

func (m *HighlightProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HighlightProductsResponse.Unmarshal(m, b)
}
func (m *HighlightProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HighlightProductsResponse.Marshal(b, m, deterministic)
}
func (m *HighlightProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighlightProductsResponse.Merge(m, src)
}
func (m *HighlightProductsResponse) XXX_Size() int {
	return xxx_messageInfo_HighlightProductsResponse.Size(m)
}
func (m *HighlightProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HighlightProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HighlightProductsResponse proto.InternalMessageInfo

func (m *HighlightProductsResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *HighlightProductsResponse) GetData() []*HighlightProductsResponseItem {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProductRequest)(nil), "product.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "product.CreateProductResponse")
	proto.RegisterType((*DetailProductRequest)(nil), "product.DetailProductRequest")
	proto.RegisterType((*DetailProductResponse)(nil), "product.DetailProductResponse")
	proto.RegisterType((*EditProductRequest)(nil), "product.EditProductRequest")
	proto.RegisterType((*EditProductResponse)(nil), "product.EditProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "product.DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "product.DeleteProductResponse")
	proto.RegisterType((*ListProductRequest)(nil), "product.ListProductRequest")
	proto.RegisterType((*ListProductResponseItem)(nil), "product.ListProductResponseItem")
	proto.RegisterType((*ListProductResponse)(nil), "product.ListProductResponse")
	proto.RegisterType((*ListProductAdminRequest)(nil), "product.ListProductAdminRequest")
	proto.RegisterType((*ListProductAdminResponseItem)(nil), "product.ListProductAdminResponseItem")
	proto.RegisterType((*ListProductAdminResponse)(nil), "product.ListProductAdminResponse")
	proto.RegisterType((*HighlightProductsRequest)(nil), "product.HighlightProductsRequest")
	proto.RegisterType((*HighlightProductsResponseItem)(nil), "product.HighlightProductsResponseItem")
	proto.RegisterType((*HighlightProductsResponse)(nil), "product.HighlightProductsResponse")
}

func init() { proto.RegisterFile("product/product.proto", fileDescriptor_5f9f5dc4dd6fa6d7) }

var fileDescriptor_5f9f5dc4dd6fa6d7 = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xc7, 0x7f, 0x4e, 0xd3, 0xed, 0xb7, 0x53, 0x6d, 0x0c, 0xaf, 0xd3, 0xb2, 0xec, 0x0f, 0x5d,
	0x04, 0xa8, 0x48, 0xac, 0x95, 0x0a, 0x37, 0xe3, 0x6e, 0xe5, 0x8f, 0x8a, 0x84, 0xb6, 0x11, 0x40,
	0x48, 0xbb, 0x99, 0xdc, 0xc6, 0xeb, 0x2c, 0x25, 0x4d, 0x48, 0xd2, 0xdd, 0xf3, 0x0a, 0xdc, 0xc0,
	0x6b, 0x70, 0x3b, 0x24, 0xee, 0x79, 0x03, 0xde, 0x06, 0x14, 0xdb, 0x29, 0x71, 0x93, 0x76, 0xab,
	0x98, 0xd0, 0x7a, 0xd3, 0x36, 0xe7, 0xeb, 0xe3, 0xe3, 0xcf, 0xf9, 0xda, 0x0e, 0xac, 0x06, 0xa1,
	0xef, 0x0c, 0x7b, 0x71, 0x53, 0x7e, 0x37, 0x82, 0xd0, 0x8f, 0x7d, 0x3c, 0x2f, 0xff, 0x9a, 0x66,
	0xcf, 0xf7, 0x3c, 0x7f, 0xd0, 0xec, 0x92, 0x88, 0x9e, 0x84, 0x34, 0x0a, 0xfc, 0x41, 0x44, 0x85,
	0xc8, 0x5c, 0x93, 0xb1, 0x80, 0xf4, 0xd9, 0x80, 0xc4, 0xcc, 0x1f, 0xc8, 0xc0, 0x46, 0x77, 0x78,
	0xda, 0x3c, 0x27, 0x2e, 0x73, 0x48, 0x4c, 0x47, 0x3f, 0x44, 0xd0, 0xfa, 0x8e, 0xa0, 0xfa, 0x34,
	0xa4, 0x24, 0xa6, 0x47, 0x62, 0x0e, 0x9b, 0x7e, 0x18, 0xd2, 0x28, 0xc6, 0xdb, 0xa0, 0x0f, 0x88,
	0x47, 0x0d, 0x54, 0x43, 0xf5, 0x85, 0x36, 0x5c, 0x74, 0xe6, 0xc3, 0xf2, 0x32, 0x32, 0x7e, 0x21,
	0x9b, 0x3f, 0xc7, 0x0f, 0xa1, 0xe2, 0xd0, 0xa8, 0x17, 0xb2, 0x20, 0x99, 0xca, 0xd0, 0x72, 0xb2,
	0x6c, 0x18, 0xdf, 0x85, 0x72, 0x10, 0xb2, 0x1e, 0x35, 0x4a, 0x35, 0x54, 0x47, 0xed, 0xa5, 0x8b,
	0x4e, 0x05, 0x2f, 0x3c, 0xf8, 0x4f, 0x7e, 0x6c, 0x11, 0xc4, 0x2d, 0xb8, 0xc5, 0x3c, 0xd2, 0xa7,
	0x27, 0xa7, 0xcc, 0xa5, 0x27, 0x7c, 0x7a, 0x3d, 0x97, 0x77, 0x91, 0x4b, 0x5e, 0x30, 0x97, 0x1e,
	0x10, 0x8f, 0x5a, 0xaf, 0x61, 0x75, 0xac, 0x7e, 0x41, 0x05, 0xd7, 0x41, 0x4f, 0x30, 0xf1, 0x05,
	0x54, 0x5a, 0xd5, 0x86, 0xc0, 0xd3, 0x68, 0x93, 0x88, 0xa6, 0x1a, 0x9b, 0x2b, 0xf0, 0x12, 0x68,
	0xcc, 0x11, 0x2b, 0xb0, 0x35, 0xe6, 0x58, 0x2d, 0xa8, 0x3e, 0xa3, 0x31, 0x61, 0xee, 0x18, 0x12,
	0x93, 0xeb, 0xf2, 0x40, 0x92, 0x31, 0x17, 0x08, 0x56, 0xc7, 0x06, 0xfd, 0x6d, 0x1d, 0x18, 0xcb,
	0x16, 0x94, 0xf8, 0x13, 0x81, 0xbd, 0xa6, 0x62, 0xe7, 0x78, 0x54, 0xd4, 0xd5, 0x14, 0x75, 0x39,
	0x41, 0x9d, 0xa2, 0xdd, 0x80, 0x05, 0x81, 0x76, 0x18, 0xba, 0xc6, 0x1c, 0x1f, 0xf5, 0x3f, 0x7f,
	0xf0, 0x2e, 0x74, 0xad, 0x9f, 0x08, 0xf0, 0x73, 0x87, 0xc5, 0x57, 0x5f, 0xef, 0xc8, 0x1e, 0xda,
	0xd5, 0xec, 0x51, 0xba, 0xa2, 0x3d, 0xf4, 0x19, 0xed, 0x51, 0xbe, 0xcc, 0x1e, 0x87, 0xb0, 0xa2,
	0xac, 0xec, 0x7a, 0xcc, 0xe1, 0xd2, 0xdc, 0x7e, 0x99, 0x66, 0x8e, 0xfd, 0xc4, 0x1b, 0xca, 0x98,
	0x59, 0xcb, 0xb0, 0x0e, 0x01, 0xbf, 0x62, 0xd1, 0x78, 0x87, 0xf6, 0x00, 0xfe, 0x6c, 0x77, 0x99,
	0x65, 0x3d, 0xcd, 0x72, 0x34, 0x8a, 0x48, 0xb9, 0x9d, 0x11, 0x5b, 0x9f, 0x10, 0xac, 0x29, 0x19,
	0xc5, 0x74, 0x2f, 0x63, 0xea, 0xc9, 0x35, 0xa3, 0x9c, 0x11, 0xb5, 0xc9, 0x46, 0x2c, 0x4d, 0x31,
	0xa2, 0x3e, 0xd1, 0x88, 0xe5, 0x31, 0x23, 0x7e, 0x45, 0xb0, 0x52, 0x50, 0xd4, 0x0c, 0xed, 0x7a,
	0xa2, 0x10, 0xd1, 0xb8, 0xde, 0x2c, 0x22, 0x22, 0x47, 0x65, 0xd4, 0xf8, 0x31, 0xe8, 0x0e, 0x89,
	0x89, 0x51, 0xaa, 0x95, 0xea, 0x95, 0x56, 0xad, 0x91, 0x1e, 0xc2, 0x13, 0x30, 0xd9, 0x5c, 0x6d,
	0xbd, 0x55, 0x38, 0xee, 0x3b, 0x1e, 0x1b, 0x5c, 0x43, 0x7b, 0x3e, 0x23, 0xd8, 0xcc, 0xa7, 0xbd,
	0x09, 0x3d, 0xfa, 0x86, 0xc0, 0x98, 0x54, 0xd9, 0x3f, 0x6a, 0xd4, 0x9e, 0xd2, 0xa8, 0x7b, 0x45,
	0x8d, 0xca, 0x01, 0x93, 0xdd, 0x32, 0xc1, 0xe8, 0xb0, 0xfe, 0x99, 0xcb, 0xfa, 0x67, 0xa9, 0x34,
	0x92, 0xfc, 0xad, 0x2f, 0x08, 0xb6, 0x0a, 0x82, 0x37, 0x01, 0xfa, 0x47, 0x04, 0xeb, 0x13, 0x4b,
	0x9b, 0x89, 0xba, 0x20, 0xa7, 0x71, 0x72, 0xf7, 0x47, 0xe4, 0xa6, 0x2e, 0x5b, 0xa0, 0x6b, 0xfd,
	0xd0, 0x61, 0x49, 0x86, 0xdf, 0xd0, 0xf0, 0x3c, 0xa9, 0xf9, 0x00, 0x16, 0x95, 0xcb, 0x17, 0x6f,
	0x8d, 0x32, 0x16, 0xbd, 0x54, 0x98, 0xdb, 0x93, 0xc2, 0x72, 0x21, 0x07, 0xb0, 0xa8, 0x5c, 0xa2,
	0x99, 0x7c, 0x45, 0x37, 0x72, 0x26, 0x5f, 0xf1, 0xdd, 0xdb, 0x81, 0x4a, 0xe6, 0xf4, 0xc7, 0x1b,
	0x23, 0x79, 0xfe, 0xb6, 0x33, 0x37, 0x8b, 0x83, 0xd9, 0xca, 0x32, 0x47, 0xb8, 0x52, 0x59, 0xfe,
	0x3a, 0x50, 0x2a, 0x2b, 0x3a, 0xf9, 0x3b, 0x50, 0xc9, 0xb8, 0x35, 0x53, 0x59, 0xfe, 0x94, 0xcf,
	0x54, 0x56, 0x74, 0x36, 0xbe, 0x87, 0xe5, 0x71, 0xdf, 0xe3, 0xda, 0x94, 0x2d, 0x21, 0x72, 0xee,
	0x5c, 0xba, 0x69, 0xf0, 0x31, 0xdc, 0xce, 0xd9, 0x02, 0xef, 0x4c, 0xb3, 0x8c, 0x48, 0x6d, 0x5d,
	0xee, 0xaa, 0xf6, 0xce, 0xf1, 0x9d, 0xbe, 0xbf, 0xdb, 0x0f, 0x83, 0xde, 0x2e, 0x4d, 0xdc, 0x4a,
	0xc3, 0x1e, 0xdd, 0xed, 0xd2, 0x66, 0xd0, 0x4d, 0x5f, 0x7d, 0xbb, 0x73, 0xfc, 0x05, 0xf5, 0xd1,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x08, 0x2a, 0x8f, 0x14, 0x0b, 0x00, 0x00,
}
