// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

package auth

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-grpc-ecommerce-be/pb/common"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string   `protobuf:"bytes,4,opt,name=password_confirmation,json=passwordConfirmation,proto3" json:"password_confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

type RegisterResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AccessToken          string               `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{4}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{5}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type ChangePasswordRequest struct {
	OldPassword             string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword             string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	NewPasswordConfirmation string   `protobuf:"bytes,3,opt,name=new_password_confirmation,json=newPasswordConfirmation,proto3" json:"new_password_confirmation,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{6}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPasswordConfirmation() string {
	if m != nil {
		return m.NewPasswordConfirmation
	}
	return ""
}

type ChangePasswordResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{7}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type GetProfileRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{8}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

type GetProfileResponse struct {
	Base                 *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName             string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	RoleCode             string                 `protobuf:"bytes,5,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	MemberSince          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=member_since,json=memberSince,proto3" json:"member_since,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetProfileResponse) Reset()         { *m = GetProfileResponse{} }
func (m *GetProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfileResponse) ProtoMessage()    {}
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{9}
}

func (m *GetProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileResponse.Unmarshal(m, b)
}
func (m *GetProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileResponse.Merge(m, src)
}
func (m *GetProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfileResponse.Size(m)
}
func (m *GetProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileResponse proto.InternalMessageInfo

func (m *GetProfileResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GetProfileResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetProfileResponse) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *GetProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetProfileResponse) GetRoleCode() string {
	if m != nil {
		return m.RoleCode
	}
	return ""
}

func (m *GetProfileResponse) GetMemberSince() *timestamppb.Timestamp {
	if m != nil {
		return m.MemberSince
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "auth.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "auth.LogoutResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "auth.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "auth.ChangePasswordResponse")
	proto.RegisterType((*GetProfileRequest)(nil), "auth.GetProfileRequest")
	proto.RegisterType((*GetProfileResponse)(nil), "auth.GetProfileResponse")
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor_712ec48c1eaf43a2) }

var fileDescriptor_712ec48c1eaf43a2 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0xfb, 0x6b, 0xd2, 0x66, 0x92, 0x5f, 0x5b, 0xb6, 0x69, 0x6b, 0x9c, 0x8a, 0x3f, 0x3e,
	0x40, 0x2f, 0x71, 0x50, 0x7b, 0x02, 0x81, 0x2a, 0x52, 0x09, 0x8a, 0x40, 0xa8, 0x72, 0x7b, 0xaa,
	0x90, 0xcc, 0xc6, 0x9e, 0xb8, 0x16, 0xb6, 0x37, 0xec, 0xda, 0xed, 0xbb, 0x55, 0xea, 0x99, 0x37,
	0xe1, 0x35, 0x40, 0xde, 0xf5, 0x26, 0x4e, 0x5c, 0x10, 0xb9, 0x44, 0xeb, 0x99, 0x6f, 0x26, 0x33,
	0xdf, 0x7c, 0x33, 0xb0, 0x49, 0xf3, 0xec, 0x6a, 0x50, 0xfc, 0x38, 0x13, 0xce, 0x32, 0x46, 0x56,
	0x8b, 0xb7, 0x65, 0xf9, 0x2c, 0x49, 0x58, 0x3a, 0x18, 0x51, 0x81, 0x1e, 0x47, 0x31, 0x61, 0xa9,
	0x40, 0x85, 0xb0, 0x7a, 0xa3, 0x7c, 0x3c, 0xb8, 0xa6, 0x71, 0x14, 0xd0, 0x0c, 0xa7, 0x8f, 0xd2,
	0xf9, 0x38, 0x64, 0x2c, 0x8c, 0x71, 0x20, 0xbf, 0x0a, 0x60, 0x16, 0x25, 0x28, 0x32, 0x9a, 0x4c,
	0x14, 0xc0, 0xfe, 0x61, 0xc0, 0xa6, 0x8b, 0x61, 0x24, 0x32, 0xe4, 0x2e, 0x7e, 0xcf, 0x51, 0x64,
	0xe4, 0x39, 0xb4, 0xc6, 0x79, 0x1c, 0x7b, 0x29, 0x4d, 0xd0, 0x34, 0x9e, 0x18, 0x07, 0xad, 0x21,
	0xdc, 0x9e, 0xae, 0xf1, 0xc6, 0x96, 0x61, 0xfe, 0x32, 0xdc, 0xf5, 0xc2, 0xf9, 0x99, 0x26, 0x48,
	0x6c, 0x68, 0x60, 0x42, 0xa3, 0xd8, 0x5c, 0x91, 0xa0, 0xce, 0xed, 0x69, 0x8b, 0xaf, 0x49, 0xd0,
	0x57, 0xc3, 0x55, 0x2e, 0xf2, 0x0c, 0xd6, 0x27, 0x54, 0x88, 0x1b, 0xc6, 0x03, 0xf3, 0xbf, 0x7a,
	0x2e, 0xed, 0x23, 0xc7, 0xb0, 0xa3, 0xdf, 0x9e, 0xcf, 0xd2, 0x71, 0xc4, 0x13, 0x9a, 0x45, 0x2c,
	0x35, 0x57, 0x6b, 0x41, 0x5d, 0x0d, 0x3c, 0xa9, 0xe0, 0xec, 0xd7, 0xb0, 0x35, 0x6b, 0x44, 0x31,
	0x44, 0x0e, 0x60, 0xb5, 0xa0, 0x4c, 0x36, 0xd1, 0x3e, 0xec, 0x3a, 0x8a, 0x46, 0x67, 0x48, 0x05,
	0x6a, 0x8c, 0x2b, 0x11, 0xf6, 0x25, 0x74, 0x3e, 0xb1, 0x30, 0x4a, 0x35, 0x07, 0xd3, 0xd6, 0x8c,
	0x7f, 0x6b, 0x6d, 0xe5, 0xcf, 0xad, 0xd9, 0x5f, 0xe0, 0xff, 0x32, 0xf7, 0xb2, 0x65, 0x91, 0xa7,
	0xd0, 0xa1, 0xbe, 0x8f, 0x42, 0x78, 0x19, 0xfb, 0x86, 0xa9, 0xfa, 0x1b, 0xb7, 0xad, 0x6c, 0x17,
	0x85, 0xc9, 0xde, 0x94, 0xd9, 0x59, 0x9e, 0x95, 0xa5, 0xdb, 0xaf, 0x60, 0x43, 0x1b, 0x96, 0xa6,
	0xe1, 0xce, 0x80, 0x9d, 0x93, 0x2b, 0x9a, 0x86, 0x78, 0x56, 0x56, 0xaf, 0x09, 0xe9, 0x43, 0x87,
	0xc5, 0x81, 0x37, 0x6d, 0xb8, 0xae, 0x8b, 0x36, 0x8b, 0x03, 0x1d, 0x55, 0xc0, 0x53, 0xbc, 0xf1,
	0xfe, 0xc2, 0x4f, 0x3b, 0xc5, 0x9b, 0x29, 0xfc, 0x1d, 0x3c, 0xac, 0xc2, 0xe7, 0x15, 0x50, 0x97,
	0xcd, 0x5e, 0x25, 0x76, 0x4e, 0x04, 0x43, 0xd8, 0x5d, 0x2c, 0x7f, 0x69, 0x0e, 0xb6, 0xe1, 0xc1,
	0x7b, 0xcc, 0xce, 0x38, 0x1b, 0x47, 0x31, 0x6a, 0x52, 0x7f, 0x1a, 0x40, 0xaa, 0xd6, 0xa5, 0x27,
	0xb9, 0x07, 0x6b, 0xb9, 0x40, 0xee, 0x45, 0x25, 0x17, 0x6e, 0xb3, 0xf8, 0xfc, 0x10, 0x90, 0x5e,
	0x75, 0xdb, 0x64, 0xab, 0x95, 0x0d, 0xeb, 0x6a, 0x19, 0xca, 0x2d, 0xd0, 0xc2, 0xeb, 0x41, 0x8b,
	0xb3, 0x18, 0x3d, 0x9f, 0x05, 0x68, 0x36, 0x54, 0x48, 0x61, 0x38, 0x61, 0x01, 0x92, 0x37, 0xd0,
	0x49, 0x30, 0x19, 0x21, 0xf7, 0x44, 0x94, 0xfa, 0x68, 0x36, 0x65, 0x69, 0x96, 0xa3, 0x2e, 0x81,
	0xa3, 0x2f, 0x81, 0x73, 0xa1, 0x2f, 0x81, 0xdb, 0x56, 0xf8, 0xf3, 0x02, 0x7e, 0x78, 0xb7, 0x02,
	0xed, 0xb7, 0x79, 0x76, 0x75, 0x8e, 0xfc, 0x3a, 0xf2, 0x91, 0xbc, 0x84, 0x75, 0xbd, 0x56, 0x64,
	0xc7, 0x91, 0x97, 0x69, 0xe1, 0x5e, 0x58, 0xbb, 0x8b, 0xe6, 0x92, 0x9c, 0x17, 0xd0, 0x90, 0xba,
	0x27, 0x44, 0x01, 0xaa, 0x0b, 0x66, 0x6d, 0xcf, 0xd9, 0xca, 0x88, 0x23, 0x68, 0x2a, 0xe9, 0x92,
	0x99, 0x7b, 0xa6, 0x6c, 0xab, 0x3b, 0x6f, 0x2c, 0x83, 0x3e, 0xc2, 0xc6, 0xfc, 0xcc, 0x49, 0x4f,
	0xe1, 0xee, 0x15, 0xb2, 0xb5, 0x7f, 0xbf, 0xb3, 0x4c, 0x76, 0x0c, 0x30, 0x1b, 0x33, 0xd9, 0x53,
	0xd8, 0x9a, 0x1c, 0x2c, 0xb3, 0xee, 0x50, 0x09, 0x86, 0x8f, 0x2e, 0xf7, 0x43, 0xd6, 0x0f, 0xf9,
	0xc4, 0xef, 0x63, 0xa1, 0x06, 0xe4, 0x3e, 0xf6, 0x47, 0x38, 0x98, 0x8c, 0xe4, 0x59, 0x1f, 0x35,
	0xe5, 0x00, 0x8e, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x34, 0x35, 0x4a, 0x5c, 0xea, 0x05, 0x00,
	0x00,
}
