// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/service.proto

package service

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-grpc-ecommerce-be/pb/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloWorldRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{0}
}

func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(m, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloWorldResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HelloWorldResponse) Reset()         { *m = HelloWorldResponse{} }
func (m *HelloWorldResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldResponse) ProtoMessage()    {}
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{1}
}

func (m *HelloWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldResponse.Unmarshal(m, b)
}
func (m *HelloWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldResponse.Merge(m, src)
}
func (m *HelloWorldResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldResponse.Size(m)
}
func (m *HelloWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldResponse proto.InternalMessageInfo

func (m *HelloWorldResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *HelloWorldResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloWorldRequest)(nil), "service.HelloWorldRequest")
	proto.RegisterType((*HelloWorldResponse)(nil), "service.HelloWorldResponse")
}

func init() { proto.RegisterFile("service/service.proto", fileDescriptor_e51e679f9ae460e2) }

var fileDescriptor_e51e679f9ae460e2 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x94, 0x51, 0x21, 0x62, 0x7b, 0x01, 0x0b, 0xa4, 0xc8, 0x95, 0x78, 0xf4, 0xd4, 0x4b, 0x12,
	0x29, 0xfd, 0x83, 0x48, 0xa0, 0x9e, 0xc3, 0x01, 0xc4, 0x05, 0xd9, 0xe9, 0x10, 0x55, 0x4a, 0xe2,
	0xe0, 0x4d, 0xfb, 0x41, 0x7c, 0x06, 0x3f, 0x07, 0xca, 0x8b, 0x56, 0x82, 0x53, 0x4f, 0xf6, 0xce,
	0xce, 0x7a, 0x66, 0xc7, 0x74, 0xcd, 0x70, 0xbb, 0x4d, 0x86, 0x68, 0x38, 0xc3, 0xda, 0xd9, 0xc6,
	0x4a, 0x6f, 0x28, 0x95, 0xca, 0x6c, 0x59, 0xda, 0x2a, 0x32, 0x9a, 0xf1, 0xe6, 0xc0, 0xb5, 0xad,
	0x78, 0x20, 0xa9, 0x99, 0xd9, 0xbe, 0x47, 0x3b, 0x5d, 0x6c, 0xd6, 0xba, 0xc1, 0xef, 0xa5, 0x6f,
	0xce, 0x97, 0x74, 0xb9, 0x42, 0x51, 0xd8, 0x67, 0xeb, 0x8a, 0x75, 0x8a, 0x8f, 0x2d, 0xb8, 0x91,
	0x37, 0x34, 0xa9, 0x74, 0x09, 0x5f, 0xdc, 0x89, 0xc5, 0x79, 0x42, 0x5f, 0x2b, 0xcf, 0x9d, 0x5e,
	0x08, 0xff, 0x5b, 0xa4, 0x1d, 0x3e, 0x7f, 0x21, 0x79, 0x38, 0xd4, 0xab, 0xc9, 0x05, 0x4d, 0x5a,
	0xf9, 0x6e, 0x6a, 0x1a, 0x5f, 0x85, 0xbd, 0xa5, 0x30, 0xd1, 0x8c, 0x91, 0x93, 0x76, 0x0c, 0xe9,
	0x93, 0x57, 0x82, 0x59, 0xe7, 0xf0, 0x4f, 0x5a, 0x89, 0x74, 0x2c, 0xe3, 0x4f, 0x71, 0xe8, 0xe7,
	0xa9, 0xdf, 0x4e, 0x3e, 0x10, 0xed, 0x41, 0xa9, 0xc2, 0x31, 0x84, 0x3f, 0xce, 0xd5, 0xec, 0xdf,
	0xde, 0x60, 0xf0, 0x91, 0xa6, 0x7b, 0x34, 0x3e, 0xfa, 0x9d, 0xe4, 0xfe, 0xf5, 0x36, 0xb7, 0x41,
	0xee, 0xea, 0x2c, 0x40, 0xbb, 0x24, 0x5c, 0x86, 0xc0, 0x20, 0xaa, 0xcd, 0xf8, 0x3d, 0xe6, 0xac,
	0x4b, 0x77, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x7c, 0x3b, 0x13, 0xb8, 0x01, 0x00, 0x00,
}
