services:
  postgres:
    container_name: postgres-gocommerce
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres       #nama database custom
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  host:
    external: true
  local-network:
    driver: bridge
volumes:
  postgresql:
  postgresql_data:


