version: "3.9"

services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # REST di port 8080
    env_file:
      - .env
    depends_on:
      - db

  grpc:
    build:
      context: .
      dockerfile: Dockerfile-2
    ports:
      - "50051:50051" # gRPC port
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      DB_URI: ${DB_URI}
    ports:
      - "5432:5432"
