// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product/product.proto

package product

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	_ "github.com/aldian78/go-react-ecommerce/proto/pb/common"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ProductService service

func NewProductServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ProductService service

type ProductService interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...client.CallOption) (*CreateProductResponse, error)
	DetailProduct(ctx context.Context, in *DetailProductRequest, opts ...client.CallOption) (*DetailProductResponse, error)
	EditProduct(ctx context.Context, in *EditProductRequest, opts ...client.CallOption) (*EditProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...client.CallOption) (*DeleteProductResponse, error)
	ListProduct(ctx context.Context, in *ListProductRequest, opts ...client.CallOption) (*ListProductResponse, error)
	ListProductAdmin(ctx context.Context, in *ListProductAdminRequest, opts ...client.CallOption) (*ListProductAdminResponse, error)
	HighlightProducts(ctx context.Context, in *HighlightProductsRequest, opts ...client.CallOption) (*HighlightProductsResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...client.CallOption) (*CreateProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.CreateProduct", in)
	out := new(CreateProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) DetailProduct(ctx context.Context, in *DetailProductRequest, opts ...client.CallOption) (*DetailProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.DetailProduct", in)
	out := new(DetailProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) EditProduct(ctx context.Context, in *EditProductRequest, opts ...client.CallOption) (*EditProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.EditProduct", in)
	out := new(EditProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...client.CallOption) (*DeleteProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.DeleteProduct", in)
	out := new(DeleteProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) ListProduct(ctx context.Context, in *ListProductRequest, opts ...client.CallOption) (*ListProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.ListProduct", in)
	out := new(ListProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) ListProductAdmin(ctx context.Context, in *ListProductAdminRequest, opts ...client.CallOption) (*ListProductAdminResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.ListProductAdmin", in)
	out := new(ListProductAdminResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) HighlightProducts(ctx context.Context, in *HighlightProductsRequest, opts ...client.CallOption) (*HighlightProductsResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.HighlightProducts", in)
	out := new(HighlightProductsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	CreateProduct(context.Context, *CreateProductRequest, *CreateProductResponse) error
	DetailProduct(context.Context, *DetailProductRequest, *DetailProductResponse) error
	EditProduct(context.Context, *EditProductRequest, *EditProductResponse) error
	DeleteProduct(context.Context, *DeleteProductRequest, *DeleteProductResponse) error
	ListProduct(context.Context, *ListProductRequest, *ListProductResponse) error
	ListProductAdmin(context.Context, *ListProductAdminRequest, *ListProductAdminResponse) error
	HighlightProducts(context.Context, *HighlightProductsRequest, *HighlightProductsResponse) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) error {
	type productService interface {
		CreateProduct(ctx context.Context, in *CreateProductRequest, out *CreateProductResponse) error
		DetailProduct(ctx context.Context, in *DetailProductRequest, out *DetailProductResponse) error
		EditProduct(ctx context.Context, in *EditProductRequest, out *EditProductResponse) error
		DeleteProduct(ctx context.Context, in *DeleteProductRequest, out *DeleteProductResponse) error
		ListProduct(ctx context.Context, in *ListProductRequest, out *ListProductResponse) error
		ListProductAdmin(ctx context.Context, in *ListProductAdminRequest, out *ListProductAdminResponse) error
		HighlightProducts(ctx context.Context, in *HighlightProductsRequest, out *HighlightProductsResponse) error
	}
	type ProductService struct {
		productService
	}
	h := &productServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductService{h}, opts...))
}

type productServiceHandler struct {
	ProductServiceHandler
}

func (h *productServiceHandler) CreateProduct(ctx context.Context, in *CreateProductRequest, out *CreateProductResponse) error {
	return h.ProductServiceHandler.CreateProduct(ctx, in, out)
}

func (h *productServiceHandler) DetailProduct(ctx context.Context, in *DetailProductRequest, out *DetailProductResponse) error {
	return h.ProductServiceHandler.DetailProduct(ctx, in, out)
}

func (h *productServiceHandler) EditProduct(ctx context.Context, in *EditProductRequest, out *EditProductResponse) error {
	return h.ProductServiceHandler.EditProduct(ctx, in, out)
}

func (h *productServiceHandler) DeleteProduct(ctx context.Context, in *DeleteProductRequest, out *DeleteProductResponse) error {
	return h.ProductServiceHandler.DeleteProduct(ctx, in, out)
}

func (h *productServiceHandler) ListProduct(ctx context.Context, in *ListProductRequest, out *ListProductResponse) error {
	return h.ProductServiceHandler.ListProduct(ctx, in, out)
}

func (h *productServiceHandler) ListProductAdmin(ctx context.Context, in *ListProductAdminRequest, out *ListProductAdminResponse) error {
	return h.ProductServiceHandler.ListProductAdmin(ctx, in, out)
}

func (h *productServiceHandler) HighlightProducts(ctx context.Context, in *HighlightProductsRequest, out *HighlightProductsResponse) error {
	return h.ProductServiceHandler.HighlightProducts(ctx, in, out)
}
