// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: category/category.proto

package category

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	api1 "github.com/aldian78/go-react-ecommerce/proto/pb/api"
	_ "github.com/aldian78/go-react-ecommerce/proto/pb/basecommon"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CategoryService service

func NewCategoryServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CategoryService service

type CategoryService interface {
	CreateCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
	EditCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
	DeleteCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
	ListCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
}

type categoryService struct {
	c    client.Client
	name string
}

func NewCategoryService(name string, c client.Client) CategoryService {
	return &categoryService{
		c:    c,
		name: name,
	}
}

func (c *categoryService) CreateCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "CategoryService.CreateCategory", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) EditCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "CategoryService.EditCategory", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) DeleteCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "CategoryService.DeleteCategory", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) ListCategory(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "CategoryService.ListCategory", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CategoryService service

type CategoryServiceHandler interface {
	CreateCategory(context.Context, *api1.APIREQ, *api1.APIRES) error
	EditCategory(context.Context, *api1.APIREQ, *api1.APIRES) error
	DeleteCategory(context.Context, *api1.APIREQ, *api1.APIRES) error
	ListCategory(context.Context, *api1.APIREQ, *api1.APIRES) error
}

func RegisterCategoryServiceHandler(s server.Server, hdlr CategoryServiceHandler, opts ...server.HandlerOption) error {
	type categoryService interface {
		CreateCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
		EditCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
		DeleteCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
		ListCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
	}
	type CategoryService struct {
		categoryService
	}
	h := &categoryServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CategoryService{h}, opts...))
}

type categoryServiceHandler struct {
	CategoryServiceHandler
}

func (h *categoryServiceHandler) CreateCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.CategoryServiceHandler.CreateCategory(ctx, in, out)
}

func (h *categoryServiceHandler) EditCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.CategoryServiceHandler.EditCategory(ctx, in, out)
}

func (h *categoryServiceHandler) DeleteCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.CategoryServiceHandler.DeleteCategory(ctx, in, out)
}

func (h *categoryServiceHandler) ListCategory(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.CategoryServiceHandler.ListCategory(ctx, in, out)
}
