// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cart/cart.proto

package cart

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-grpc-ecommerce-be/pb/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddProductToCartRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductToCartRequest) Reset()         { *m = AddProductToCartRequest{} }
func (m *AddProductToCartRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductToCartRequest) ProtoMessage()    {}
func (*AddProductToCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{0}
}

func (m *AddProductToCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductToCartRequest.Unmarshal(m, b)
}
func (m *AddProductToCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductToCartRequest.Marshal(b, m, deterministic)
}
func (m *AddProductToCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductToCartRequest.Merge(m, src)
}
func (m *AddProductToCartRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductToCartRequest.Size(m)
}
func (m *AddProductToCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductToCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductToCartRequest proto.InternalMessageInfo

func (m *AddProductToCartRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type AddProductToCartResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddProductToCartResponse) Reset()         { *m = AddProductToCartResponse{} }
func (m *AddProductToCartResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductToCartResponse) ProtoMessage()    {}
func (*AddProductToCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{1}
}

func (m *AddProductToCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductToCartResponse.Unmarshal(m, b)
}
func (m *AddProductToCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductToCartResponse.Marshal(b, m, deterministic)
}
func (m *AddProductToCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductToCartResponse.Merge(m, src)
}
func (m *AddProductToCartResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductToCartResponse.Size(m)
}
func (m *AddProductToCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductToCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductToCartResponse proto.InternalMessageInfo

func (m *AddProductToCartResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *AddProductToCartResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListCartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCartRequest) Reset()         { *m = ListCartRequest{} }
func (m *ListCartRequest) String() string { return proto.CompactTextString(m) }
func (*ListCartRequest) ProtoMessage()    {}
func (*ListCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{2}
}

func (m *ListCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCartRequest.Unmarshal(m, b)
}
func (m *ListCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCartRequest.Marshal(b, m, deterministic)
}
func (m *ListCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCartRequest.Merge(m, src)
}
func (m *ListCartRequest) XXX_Size() int {
	return xxx_messageInfo_ListCartRequest.Size(m)
}
func (m *ListCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCartRequest proto.InternalMessageInfo

type ListCartResponseItem struct {
	CartId               string   `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName          string   `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImageUrl      string   `protobuf:"bytes,4,opt,name=product_image_url,json=productImageUrl,proto3" json:"product_image_url,omitempty"`
	ProductPrice         float64  `protobuf:"fixed64,5,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	Quantity             int64    `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCartResponseItem) Reset()         { *m = ListCartResponseItem{} }
func (m *ListCartResponseItem) String() string { return proto.CompactTextString(m) }
func (*ListCartResponseItem) ProtoMessage()    {}
func (*ListCartResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{3}
}

func (m *ListCartResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCartResponseItem.Unmarshal(m, b)
}
func (m *ListCartResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCartResponseItem.Marshal(b, m, deterministic)
}
func (m *ListCartResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCartResponseItem.Merge(m, src)
}
func (m *ListCartResponseItem) XXX_Size() int {
	return xxx_messageInfo_ListCartResponseItem.Size(m)
}
func (m *ListCartResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCartResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListCartResponseItem proto.InternalMessageInfo

func (m *ListCartResponseItem) GetCartId() string {
	if m != nil {
		return m.CartId
	}
	return ""
}

func (m *ListCartResponseItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ListCartResponseItem) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *ListCartResponseItem) GetProductImageUrl() string {
	if m != nil {
		return m.ProductImageUrl
	}
	return ""
}

func (m *ListCartResponseItem) GetProductPrice() float64 {
	if m != nil {
		return m.ProductPrice
	}
	return 0
}

func (m *ListCartResponseItem) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ListCartResponse struct {
	Base                 *common.BaseResponse    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Items                []*ListCartResponseItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListCartResponse) Reset()         { *m = ListCartResponse{} }
func (m *ListCartResponse) String() string { return proto.CompactTextString(m) }
func (*ListCartResponse) ProtoMessage()    {}
func (*ListCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{4}
}

func (m *ListCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCartResponse.Unmarshal(m, b)
}
func (m *ListCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCartResponse.Marshal(b, m, deterministic)
}
func (m *ListCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCartResponse.Merge(m, src)
}
func (m *ListCartResponse) XXX_Size() int {
	return xxx_messageInfo_ListCartResponse.Size(m)
}
func (m *ListCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCartResponse proto.InternalMessageInfo

func (m *ListCartResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListCartResponse) GetItems() []*ListCartResponseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteCartRequest struct {
	CartId               string   `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCartRequest) Reset()         { *m = DeleteCartRequest{} }
func (m *DeleteCartRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCartRequest) ProtoMessage()    {}
func (*DeleteCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{5}
}

func (m *DeleteCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCartRequest.Unmarshal(m, b)
}
func (m *DeleteCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCartRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCartRequest.Merge(m, src)
}
func (m *DeleteCartRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCartRequest.Size(m)
}
func (m *DeleteCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCartRequest proto.InternalMessageInfo

func (m *DeleteCartRequest) GetCartId() string {
	if m != nil {
		return m.CartId
	}
	return ""
}

type DeleteCartResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteCartResponse) Reset()         { *m = DeleteCartResponse{} }
func (m *DeleteCartResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCartResponse) ProtoMessage()    {}
func (*DeleteCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{6}
}

func (m *DeleteCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCartResponse.Unmarshal(m, b)
}
func (m *DeleteCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCartResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCartResponse.Merge(m, src)
}
func (m *DeleteCartResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCartResponse.Size(m)
}
func (m *DeleteCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCartResponse proto.InternalMessageInfo

func (m *DeleteCartResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type UpdateCartQuantityRequest struct {
	CartId               string   `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	NewQuantity          int64    `protobuf:"varint,2,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCartQuantityRequest) Reset()         { *m = UpdateCartQuantityRequest{} }
func (m *UpdateCartQuantityRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCartQuantityRequest) ProtoMessage()    {}
func (*UpdateCartQuantityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{7}
}

func (m *UpdateCartQuantityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCartQuantityRequest.Unmarshal(m, b)
}
func (m *UpdateCartQuantityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCartQuantityRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCartQuantityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCartQuantityRequest.Merge(m, src)
}
func (m *UpdateCartQuantityRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCartQuantityRequest.Size(m)
}
func (m *UpdateCartQuantityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCartQuantityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCartQuantityRequest proto.InternalMessageInfo

func (m *UpdateCartQuantityRequest) GetCartId() string {
	if m != nil {
		return m.CartId
	}
	return ""
}

func (m *UpdateCartQuantityRequest) GetNewQuantity() int64 {
	if m != nil {
		return m.NewQuantity
	}
	return 0
}

type UpdateCartQuantityResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateCartQuantityResponse) Reset()         { *m = UpdateCartQuantityResponse{} }
func (m *UpdateCartQuantityResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCartQuantityResponse) ProtoMessage()    {}
func (*UpdateCartQuantityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2441b477fec4958, []int{8}
}

func (m *UpdateCartQuantityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCartQuantityResponse.Unmarshal(m, b)
}
func (m *UpdateCartQuantityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCartQuantityResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCartQuantityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCartQuantityResponse.Merge(m, src)
}
func (m *UpdateCartQuantityResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCartQuantityResponse.Size(m)
}
func (m *UpdateCartQuantityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCartQuantityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCartQuantityResponse proto.InternalMessageInfo

func (m *UpdateCartQuantityResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterType((*AddProductToCartRequest)(nil), "cart.AddProductToCartRequest")
	proto.RegisterType((*AddProductToCartResponse)(nil), "cart.AddProductToCartResponse")
	proto.RegisterType((*ListCartRequest)(nil), "cart.ListCartRequest")
	proto.RegisterType((*ListCartResponseItem)(nil), "cart.ListCartResponseItem")
	proto.RegisterType((*ListCartResponse)(nil), "cart.ListCartResponse")
	proto.RegisterType((*DeleteCartRequest)(nil), "cart.DeleteCartRequest")
	proto.RegisterType((*DeleteCartResponse)(nil), "cart.DeleteCartResponse")
	proto.RegisterType((*UpdateCartQuantityRequest)(nil), "cart.UpdateCartQuantityRequest")
	proto.RegisterType((*UpdateCartQuantityResponse)(nil), "cart.UpdateCartQuantityResponse")
}

func init() { proto.RegisterFile("cart/cart.proto", fileDescriptor_a2441b477fec4958) }

var fileDescriptor_a2441b477fec4958 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6f, 0xd3, 0x3c,
	0x18, 0x7d, 0x93, 0x7e, 0x6d, 0x4f, 0xf7, 0xd2, 0xd6, 0x1a, 0xd4, 0x04, 0x36, 0x8a, 0x77, 0x13,
	0x26, 0xb5, 0x45, 0xe5, 0x06, 0x6e, 0x40, 0x94, 0x09, 0xad, 0x12, 0x42, 0x5b, 0xd8, 0x84, 0xc4,
	0x4d, 0xe5, 0x26, 0x0f, 0x55, 0xa4, 0xe6, 0x63, 0x8e, 0xbb, 0x89, 0x1f, 0xc6, 0xcd, 0x7e, 0x0c,
	0x7f, 0x05, 0xe4, 0x38, 0x49, 0xbb, 0x7e, 0x5c, 0xf4, 0x26, 0xb2, 0x9f, 0xe7, 0xf8, 0xf8, 0xf8,
	0x1c, 0xc7, 0xd0, 0x70, 0xb9, 0x90, 0x7d, 0xf5, 0xe9, 0xc5, 0x22, 0x92, 0x11, 0x29, 0xab, 0xb1,
	0x65, 0xb9, 0x51, 0x10, 0x44, 0x61, 0x7f, 0xc2, 0x13, 0x1c, 0x0b, 0x4c, 0xe2, 0x28, 0x4c, 0x50,
	0x23, 0xac, 0x67, 0x93, 0xf9, 0xcf, 0xfe, 0x2d, 0x9f, 0xf9, 0x1e, 0x97, 0x58, 0x0c, 0x74, 0x93,
	0x9d, 0x41, 0xfb, 0xa3, 0xe7, 0x5d, 0x88, 0xc8, 0x9b, 0xbb, 0xf2, 0x2a, 0xfa, 0xc4, 0x85, 0x74,
	0xf0, 0x66, 0x8e, 0x89, 0x24, 0xaf, 0x00, 0x62, 0x5d, 0x1f, 0xfb, 0x1e, 0x35, 0x3a, 0x86, 0xbd,
	0x3f, 0x84, 0xfb, 0xf3, 0x9a, 0xa8, 0x34, 0x0d, 0xfa, 0xd7, 0x70, 0xf6, 0xb3, 0xee, 0xc8, 0x63,
	0x57, 0x40, 0xd7, 0x59, 0xb4, 0x08, 0x62, 0x43, 0x59, 0xa9, 0x4a, 0x09, 0xea, 0x83, 0xc3, 0x9e,
	0x56, 0xda, 0x1b, 0xf2, 0x04, 0x73, 0x8c, 0x93, 0x22, 0xc8, 0x23, 0x30, 0x7d, 0x8f, 0x9a, 0x6a,
	0x23, 0xc7, 0xf4, 0x3d, 0xd6, 0x82, 0xc6, 0x17, 0x3f, 0x91, 0x4b, 0x9a, 0xd8, 0x1f, 0x03, 0x0e,
	0x17, 0x35, 0xbd, 0x7a, 0x24, 0x31, 0x20, 0x6d, 0xa8, 0x29, 0x23, 0x0a, 0xa5, 0x4e, 0x55, 0x4d,
	0x47, 0x1e, 0x39, 0x7a, 0x70, 0x0a, 0x4d, 0xbe, 0x50, 0x4e, 0x5e, 0xc2, 0x41, 0xde, 0x0e, 0x79,
	0x80, 0xb4, 0x94, 0x02, 0xea, 0x59, 0xed, 0x2b, 0x0f, 0x90, 0x9c, 0x42, 0xab, 0x60, 0x08, 0xf8,
	0x14, 0xc7, 0x73, 0x31, 0xa3, 0xe5, 0x14, 0xd7, 0xc8, 0x89, 0x54, 0xfd, 0x5a, 0xcc, 0xc8, 0x09,
	0xfc, 0x9f, 0x63, 0x63, 0xe1, 0xbb, 0x48, 0x2b, 0x1d, 0xc3, 0x36, 0x9c, 0x7c, 0x8f, 0x0b, 0x55,
	0x23, 0x16, 0xec, 0xdd, 0xcc, 0x79, 0x28, 0x7d, 0xf9, 0x8b, 0x56, 0x3b, 0x86, 0x5d, 0x72, 0x8a,
	0x39, 0x0b, 0xa1, 0xb9, 0x7a, 0xbe, 0x1d, 0x1c, 0x7c, 0x0d, 0x15, 0x5f, 0x62, 0x90, 0x50, 0xb3,
	0x53, 0xb2, 0xeb, 0x03, 0xab, 0x97, 0x5e, 0x94, 0x4d, 0x86, 0x39, 0x1a, 0xc8, 0xde, 0x42, 0xeb,
	0x0c, 0x67, 0x28, 0x71, 0x39, 0xf9, 0x93, 0x15, 0x33, 0x1f, 0xc4, 0x9e, 0x19, 0xcb, 0xde, 0x03,
	0x59, 0x5e, 0xb9, 0xab, 0x56, 0x36, 0x83, 0xa7, 0xd7, 0xb1, 0xba, 0x89, 0x6a, 0xfd, 0x65, 0x76,
	0xfe, 0x5d, 0x14, 0x90, 0x53, 0x38, 0x08, 0xf1, 0x6e, 0x5c, 0x78, 0xa9, 0xc2, 0x2d, 0x0d, 0x6b,
	0xf7, 0xe7, 0x65, 0x66, 0xda, 0xff, 0x39, 0xf5, 0x10, 0xef, 0x72, 0x5e, 0xf6, 0x19, 0xac, 0x4d,
	0xbb, 0xed, 0xaa, 0x7a, 0xf0, 0xdb, 0x84, 0xba, 0xa2, 0xf8, 0x86, 0xe2, 0x56, 0x65, 0x79, 0x09,
	0xcd, 0xd5, 0x9b, 0x4f, 0x8e, 0xb4, 0xed, 0x5b, 0xfe, 0x2b, 0xeb, 0x78, 0x5b, 0x3b, 0x13, 0xf3,
	0x0e, 0xf6, 0xf2, 0xc4, 0xc8, 0xe3, 0xd5, 0x04, 0x35, 0xc5, 0x93, 0xcd, 0xc1, 0x92, 0x0f, 0x00,
	0x8b, 0x4c, 0x48, 0x5b, 0xa3, 0xd6, 0xf2, 0xb5, 0xe8, 0x7a, 0x23, 0x23, 0xf8, 0x0e, 0x64, 0xdd,
	0x26, 0xf2, 0x42, 0xe3, 0xb7, 0xc6, 0x65, 0x75, 0xb6, 0x03, 0x34, 0xf1, 0xf0, 0xf8, 0xc7, 0xf3,
	0x69, 0xd4, 0x9d, 0x8a, 0xd8, 0xed, 0xa2, 0x72, 0x17, 0x85, 0x8b, 0xdd, 0x09, 0xf6, 0xe3, 0x49,
	0xfa, 0x98, 0x4d, 0xaa, 0xe9, 0x73, 0xf4, 0xe6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x13,
	0xd3, 0xa1, 0xe0, 0x04, 0x00, 0x00,
}
