// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.5
// source: product_type/product_type.proto

package ProductType

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	api "github.com/aldian78/go-react-ecommerce/proto/pb/api"
	basecommon "github.com/aldian78/go-react-ecommerce/proto/pb/basecommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductTypeRequest) Reset() {
	*x = CreateProductTypeRequest{}
	mi := &file_product_type_product_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductTypeRequest) ProtoMessage() {}

func (x *CreateProductTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateProductTypeRequest) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateProductTypeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Base          *basecommon.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductTypeResponse) Reset() {
	*x = CreateProductTypeResponse{}
	mi := &file_product_type_product_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductTypeResponse) ProtoMessage() {}

func (x *CreateProductTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateProductTypeResponse) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductTypeResponse) GetBase() *basecommon.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateProductTypeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditProductTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProductTypeRequest) Reset() {
	*x = EditProductTypeRequest{}
	mi := &file_product_type_product_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProductTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProductTypeRequest) ProtoMessage() {}

func (x *EditProductTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProductTypeRequest.ProtoReflect.Descriptor instead.
func (*EditProductTypeRequest) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{2}
}

func (x *EditProductTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditProductTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type EditProductTypeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Base          *basecommon.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProductTypeResponse) Reset() {
	*x = EditProductTypeResponse{}
	mi := &file_product_type_product_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProductTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProductTypeResponse) ProtoMessage() {}

func (x *EditProductTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProductTypeResponse.ProtoReflect.Descriptor instead.
func (*EditProductTypeResponse) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{3}
}

func (x *EditProductTypeResponse) GetBase() *basecommon.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EditProductTypeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductTypeRequest) Reset() {
	*x = DeleteProductTypeRequest{}
	mi := &file_product_type_product_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductTypeRequest) ProtoMessage() {}

func (x *DeleteProductTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductTypeRequest) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProductTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductTypeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Base          *basecommon.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductTypeResponse) Reset() {
	*x = DeleteProductTypeResponse{}
	mi := &file_product_type_product_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductTypeResponse) ProtoMessage() {}

func (x *DeleteProductTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductTypeResponse) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductTypeResponse) GetBase() *basecommon.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type ListProductTypeRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Pagination    *basecommon.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductTypeRequest) Reset() {
	*x = ListProductTypeRequest{}
	mi := &file_product_type_product_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductTypeRequest) ProtoMessage() {}

func (x *ListProductTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductTypeRequest.ProtoReflect.Descriptor instead.
func (*ListProductTypeRequest) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductTypeRequest) GetPagination() *basecommon.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListProductTypeResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductTypeResponseItem) Reset() {
	*x = ListProductTypeResponseItem{}
	mi := &file_product_type_product_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductTypeResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductTypeResponseItem) ProtoMessage() {}

func (x *ListProductTypeResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductTypeResponseItem.ProtoReflect.Descriptor instead.
func (*ListProductTypeResponseItem) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductTypeResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListProductTypeResponseItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListProductTypeResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Base          *basecommon.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pagination    *basecommon.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data          []*ListProductTypeResponseItem `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductTypeResponse) Reset() {
	*x = ListProductTypeResponse{}
	mi := &file_product_type_product_type_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductTypeResponse) ProtoMessage() {}

func (x *ListProductTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_type_product_type_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductTypeResponse.ProtoReflect.Descriptor instead.
func (*ListProductTypeResponse) Descriptor() ([]byte, []int) {
	return file_product_type_product_type_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductTypeResponse) GetBase() *basecommon.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ListProductTypeResponse) GetPagination() *basecommon.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProductTypeResponse) GetData() []*ListProductTypeResponseItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_product_type_product_type_proto protoreflect.FileDescriptor

var file_product_type_product_type_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x1a,
	0x1e, 0x62, 0x61, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x62, 0x61, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x62, 0x75,
	0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0a, 0xba, 0x48, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0xff, 0x01, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x59, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x54, 0x0a, 0x16, 0x45, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xba, 0x48, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0xff,
	0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0a, 0xba, 0x48, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0xff, 0x01, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x57, 0x0a, 0x17, 0x45, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36,
	0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xba, 0x48, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18,
	0xff, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x22, 0x57, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0a, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x1b, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xc6, 0x01,
	0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xcc, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x45, 0x51, 0x1a,
	0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x45, 0x53, 0x12, 0x2b, 0x0a, 0x0f,
	0x45, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x45, 0x51, 0x1a, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x45, 0x53, 0x12, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x45, 0x51, 0x1a, 0x0b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x45, 0x53, 0x12, 0x2b, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x45, 0x51, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x50, 0x49, 0x52, 0x45, 0x53, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x64, 0x69, 0x61, 0x6e, 0x37, 0x38, 0x2f, 0x67, 0x6f, 0x2d,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x2d, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_product_type_product_type_proto_rawDescOnce sync.Once
	file_product_type_product_type_proto_rawDescData []byte
)

func file_product_type_product_type_proto_rawDescGZIP() []byte {
	file_product_type_product_type_proto_rawDescOnce.Do(func() {
		file_product_type_product_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_type_product_type_proto_rawDesc), len(file_product_type_product_type_proto_rawDesc)))
	})
	return file_product_type_product_type_proto_rawDescData
}

var file_product_type_product_type_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_product_type_product_type_proto_goTypes = []any{
	(*CreateProductTypeRequest)(nil),      // 0: product_type.CreateProductTypeRequest
	(*CreateProductTypeResponse)(nil),     // 1: product_type.CreateProductTypeResponse
	(*EditProductTypeRequest)(nil),        // 2: product_type.EditProductTypeRequest
	(*EditProductTypeResponse)(nil),       // 3: product_type.EditProductTypeResponse
	(*DeleteProductTypeRequest)(nil),      // 4: product_type.DeleteProductTypeRequest
	(*DeleteProductTypeResponse)(nil),     // 5: product_type.DeleteProductTypeResponse
	(*ListProductTypeRequest)(nil),        // 6: product_type.ListProductTypeRequest
	(*ListProductTypeResponseItem)(nil),   // 7: product_type.ListProductTypeResponseItem
	(*ListProductTypeResponse)(nil),       // 8: product_type.ListProductTypeResponse
	(*basecommon.BaseResponse)(nil),       // 9: basecommon.BaseResponse
	(*basecommon.PaginationRequest)(nil),  // 10: basecommon.PaginationRequest
	(*basecommon.PaginationResponse)(nil), // 11: basecommon.PaginationResponse
	(*api.APIREQ)(nil),                    // 12: api.APIREQ
	(*api.APIRES)(nil),                    // 13: api.APIRES
}
var file_product_type_product_type_proto_depIdxs = []int32{
	9,  // 0: product_type.CreateProductTypeResponse.base:type_name -> basecommon.BaseResponse
	9,  // 1: product_type.EditProductTypeResponse.base:type_name -> basecommon.BaseResponse
	9,  // 2: product_type.DeleteProductTypeResponse.base:type_name -> basecommon.BaseResponse
	10, // 3: product_type.ListProductTypeRequest.pagination:type_name -> basecommon.PaginationRequest
	9,  // 4: product_type.ListProductTypeResponse.base:type_name -> basecommon.BaseResponse
	11, // 5: product_type.ListProductTypeResponse.pagination:type_name -> basecommon.PaginationResponse
	7,  // 6: product_type.ListProductTypeResponse.data:type_name -> product_type.ListProductTypeResponseItem
	12, // 7: product_type.ProductTypeService.CreateProductType:input_type -> api.APIREQ
	12, // 8: product_type.ProductTypeService.EditProductType:input_type -> api.APIREQ
	12, // 9: product_type.ProductTypeService.DeleteProductType:input_type -> api.APIREQ
	12, // 10: product_type.ProductTypeService.ListProductType:input_type -> api.APIREQ
	13, // 11: product_type.ProductTypeService.CreateProductType:output_type -> api.APIRES
	13, // 12: product_type.ProductTypeService.EditProductType:output_type -> api.APIRES
	13, // 13: product_type.ProductTypeService.DeleteProductType:output_type -> api.APIRES
	13, // 14: product_type.ProductTypeService.ListProductType:output_type -> api.APIRES
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_product_type_product_type_proto_init() }
func file_product_type_product_type_proto_init() {
	if File_product_type_product_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_type_product_type_proto_rawDesc), len(file_product_type_product_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_type_product_type_proto_goTypes,
		DependencyIndexes: file_product_type_product_type_proto_depIdxs,
		MessageInfos:      file_product_type_product_type_proto_msgTypes,
	}.Build()
	File_product_type_product_type_proto = out.File
	file_product_type_product_type_proto_goTypes = nil
	file_product_type_product_type_proto_depIdxs = nil
}
