// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product_type/product_type.proto

package ProductType

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	api1 "github.com/aldian78/go-react-ecommerce/proto/pb/api"
	_ "github.com/aldian78/go-react-ecommerce/proto/pb/basecommon"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ProductTypeService service

func NewProductTypeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ProductTypeService service

type ProductTypeService interface {
	CreateProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
	EditProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
	DeleteProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
	ListProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error)
}

type productTypeService struct {
	c    client.Client
	name string
}

func NewProductTypeService(name string, c client.Client) ProductTypeService {
	return &productTypeService{
		c:    c,
		name: name,
	}
}

func (c *productTypeService) CreateProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "ProductTypeService.CreateProductType", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeService) EditProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "ProductTypeService.EditProductType", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeService) DeleteProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "ProductTypeService.DeleteProductType", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeService) ListProductType(ctx context.Context, in *api1.APIREQ, opts ...client.CallOption) (*api1.APIRES, error) {
	req := c.c.NewRequest(c.name, "ProductTypeService.ListProductType", in)
	out := new(api1.APIRES)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductTypeService service

type ProductTypeServiceHandler interface {
	CreateProductType(context.Context, *api1.APIREQ, *api1.APIRES) error
	EditProductType(context.Context, *api1.APIREQ, *api1.APIRES) error
	DeleteProductType(context.Context, *api1.APIREQ, *api1.APIRES) error
	ListProductType(context.Context, *api1.APIREQ, *api1.APIRES) error
}

func RegisterProductTypeServiceHandler(s server.Server, hdlr ProductTypeServiceHandler, opts ...server.HandlerOption) error {
	type productTypeService interface {
		CreateProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
		EditProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
		DeleteProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
		ListProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error
	}
	type ProductTypeService struct {
		productTypeService
	}
	h := &productTypeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductTypeService{h}, opts...))
}

type productTypeServiceHandler struct {
	ProductTypeServiceHandler
}

func (h *productTypeServiceHandler) CreateProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.ProductTypeServiceHandler.CreateProductType(ctx, in, out)
}

func (h *productTypeServiceHandler) EditProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.ProductTypeServiceHandler.EditProductType(ctx, in, out)
}

func (h *productTypeServiceHandler) DeleteProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.ProductTypeServiceHandler.DeleteProductType(ctx, in, out)
}

func (h *productTypeServiceHandler) ListProductType(ctx context.Context, in *api1.APIREQ, out *api1.APIRES) error {
	return h.ProductTypeServiceHandler.ListProductType(ctx, in, out)
}
