// Code generated by protoc-gen-go. DO NOT EDIT.
// source: newsletter/newsletter.proto

package newsletter

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-grpc-ecommerce-be/pb/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubcribeNewsletterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubcribeNewsletterRequest) Reset()         { *m = SubcribeNewsletterRequest{} }
func (m *SubcribeNewsletterRequest) String() string { return proto.CompactTextString(m) }
func (*SubcribeNewsletterRequest) ProtoMessage()    {}
func (*SubcribeNewsletterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa0ea3fb4637b8fd, []int{0}
}

func (m *SubcribeNewsletterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubcribeNewsletterRequest.Unmarshal(m, b)
}
func (m *SubcribeNewsletterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubcribeNewsletterRequest.Marshal(b, m, deterministic)
}
func (m *SubcribeNewsletterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubcribeNewsletterRequest.Merge(m, src)
}
func (m *SubcribeNewsletterRequest) XXX_Size() int {
	return xxx_messageInfo_SubcribeNewsletterRequest.Size(m)
}
func (m *SubcribeNewsletterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubcribeNewsletterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubcribeNewsletterRequest proto.InternalMessageInfo

func (m *SubcribeNewsletterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SubcribeNewsletterRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type SubcribeNewsletterResponse struct {
	Base                 *common.BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubcribeNewsletterResponse) Reset()         { *m = SubcribeNewsletterResponse{} }
func (m *SubcribeNewsletterResponse) String() string { return proto.CompactTextString(m) }
func (*SubcribeNewsletterResponse) ProtoMessage()    {}
func (*SubcribeNewsletterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa0ea3fb4637b8fd, []int{1}
}

func (m *SubcribeNewsletterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubcribeNewsletterResponse.Unmarshal(m, b)
}
func (m *SubcribeNewsletterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubcribeNewsletterResponse.Marshal(b, m, deterministic)
}
func (m *SubcribeNewsletterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubcribeNewsletterResponse.Merge(m, src)
}
func (m *SubcribeNewsletterResponse) XXX_Size() int {
	return xxx_messageInfo_SubcribeNewsletterResponse.Size(m)
}
func (m *SubcribeNewsletterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubcribeNewsletterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubcribeNewsletterResponse proto.InternalMessageInfo

func (m *SubcribeNewsletterResponse) GetBase() *common.BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterType((*SubcribeNewsletterRequest)(nil), "newsletter.SubcribeNewsletterRequest")
	proto.RegisterType((*SubcribeNewsletterResponse)(nil), "newsletter.SubcribeNewsletterResponse")
}

func init() { proto.RegisterFile("newsletter/newsletter.proto", fileDescriptor_fa0ea3fb4637b8fd) }

var fileDescriptor_fa0ea3fb4637b8fd = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4e, 0xb3, 0x40,
	0x14, 0xc5, 0xc3, 0x97, 0xaf, 0x56, 0xae, 0x2e, 0x74, 0x74, 0x81, 0x74, 0x63, 0x88, 0x7f, 0xba,
	0x01, 0x92, 0xfa, 0x06, 0x2c, 0x4c, 0x57, 0x5d, 0xc0, 0xce, 0x4d, 0x9d, 0xa1, 0xa7, 0x95, 0x04,
	0x18, 0x9c, 0x81, 0x1a, 0x5f, 0xad, 0x2f, 0xa7, 0x61, 0x26, 0x96, 0xc6, 0x68, 0xdc, 0xdd, 0xcc,
	0xf9, 0xcd, 0xbd, 0xe7, 0x9e, 0x4b, 0x93, 0x1a, 0x6f, 0xba, 0x44, 0xdb, 0x42, 0xc5, 0x43, 0x19,
	0x35, 0x4a, 0xb6, 0x92, 0xd1, 0xf0, 0xe2, 0xfb, 0xb9, 0xac, 0x2a, 0x59, 0xc7, 0x82, 0x6b, 0x2c,
	0x15, 0x74, 0x23, 0x6b, 0x0d, 0xcb, 0xf9, 0x13, 0xd1, 0xad, 0xe3, 0x2d, 0x2f, 0x8b, 0x15, 0x6f,
	0xb1, 0x2f, 0xac, 0x18, 0xbc, 0xd0, 0x55, 0xd6, 0x89, 0x5c, 0x15, 0x02, 0x8b, 0x7d, 0xbb, 0x14,
	0xaf, 0x1d, 0x74, 0xcb, 0x02, 0x1a, 0xa1, 0xe2, 0x45, 0xe9, 0x39, 0xd7, 0xce, 0xd4, 0x4d, 0x4e,
	0x77, 0x73, 0x57, 0x8d, 0xcf, 0x1c, 0xef, 0xc3, 0x79, 0x76, 0x52, 0x2b, 0xb1, 0x7b, 0x72, 0xd7,
	0x5d, 0x59, 0x2e, 0x6b, 0x5e, 0xc1, 0xfb, 0x67, 0x38, 0xda, 0xcd, 0xc7, 0x6a, 0x64, 0xb8, 0xf4,
	0xb8, 0x17, 0x17, 0xbc, 0x42, 0xf0, 0x48, 0xfe, 0x4f, 0x93, 0xac, 0x55, 0x36, 0xa5, 0xff, 0xbd,
	0x77, 0x33, 0xe9, 0x64, 0x76, 0x19, 0xd9, 0x7d, 0xa2, 0x84, 0x6b, 0x7c, 0x31, 0xa9, 0x21, 0x66,
	0xef, 0x74, 0x3e, 0xfc, 0xcf, 0xa0, 0xb6, 0x45, 0x0e, 0xb6, 0xa2, 0x8b, 0xac, 0x13, 0xfa, 0x5b,
	0x77, 0x76, 0x1b, 0x1d, 0xa4, 0xf6, 0xeb, 0x9e, 0xfe, 0xdd, 0x5f, 0x98, 0x35, 0x90, 0xdc, 0x3c,
	0x05, 0x1b, 0x19, 0x6e, 0x54, 0x93, 0x87, 0xe8, 0x0d, 0x42, 0xe5, 0x08, 0x05, 0xe2, 0x46, 0x1c,
	0x5c, 0x47, 0x1c, 0x99, 0x64, 0x1f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xbb, 0xad, 0x9b,
	0xbd, 0x01, 0x00, 0x00,
}
