// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/base_response.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidationError struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationError) Reset()         { *m = ValidationError{} }
func (m *ValidationError) String() string { return proto.CompactTextString(m) }
func (*ValidationError) ProtoMessage()    {}
func (*ValidationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddb202f5e5c0bf6a, []int{0}
}

func (m *ValidationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationError.Unmarshal(m, b)
}
func (m *ValidationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationError.Marshal(b, m, deterministic)
}
func (m *ValidationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationError.Merge(m, src)
}
func (m *ValidationError) XXX_Size() int {
	return xxx_messageInfo_ValidationError.Size(m)
}
func (m *ValidationError) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationError.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationError proto.InternalMessageInfo

func (m *ValidationError) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ValidationError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BaseResponse struct {
	StatusCode           int64              `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsError              bool               `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ValidationErrors     []*ValidationError `protobuf:"bytes,4,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddb202f5e5c0bf6a, []int{1}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *BaseResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BaseResponse) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *BaseResponse) GetValidationErrors() []*ValidationError {
	if m != nil {
		return m.ValidationErrors
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidationError)(nil), "common.ValidationError")
	proto.RegisterType((*BaseResponse)(nil), "common.BaseResponse")
}

func init() { proto.RegisterFile("common/base_response.proto", fileDescriptor_ddb202f5e5c0bf6a) }

var fileDescriptor_ddb202f5e5c0bf6a = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0xd5, 0xdd, 0x75, 0x56, 0x50, 0x83, 0x60, 0xf4, 0xa0, 0x65, 0x4f, 0xbd, 0xb4,
	0x05, 0x7d, 0x02, 0x57, 0x7d, 0x81, 0x1c, 0x3c, 0x78, 0x29, 0x69, 0x32, 0x96, 0xc0, 0xb6, 0x13,
	0x32, 0x71, 0x1f, 0xca, 0xa7, 0x94, 0x36, 0x2a, 0x28, 0x78, 0xfc, 0xff, 0x64, 0xfe, 0xf9, 0xfe,
	0x81, 0x6b, 0x43, 0xc3, 0x40, 0x63, 0xd3, 0x69, 0xc6, 0x36, 0x20, 0x7b, 0x1a, 0x19, 0x6b, 0x1f,
	0x28, 0x92, 0x58, 0xa4, 0xb7, 0xcd, 0x03, 0x9c, 0xbe, 0xe8, 0x9d, 0xb3, 0x3a, 0x3a, 0x1a, 0x9f,
	0x43, 0xa0, 0x20, 0x2e, 0xe0, 0xe8, 0xcd, 0xe1, 0xce, 0xca, 0xac, 0xc8, 0xca, 0x63, 0x95, 0x84,
	0x90, 0xb0, 0x1c, 0x90, 0x59, 0xf7, 0x28, 0x0f, 0x66, 0xff, 0x5b, 0x6e, 0x3e, 0x32, 0x38, 0xd9,
	0x6a, 0x46, 0xf5, 0xb5, 0x41, 0xdc, 0xc2, 0x9a, 0xa3, 0x8e, 0xef, 0xdc, 0x1a, 0xb2, 0x38, 0xc7,
	0xe4, 0x0a, 0x92, 0xf5, 0x48, 0x16, 0xff, 0xcf, 0x12, 0x57, 0xb0, 0x72, 0xdc, 0xe2, 0xc4, 0x21,
	0xf3, 0x22, 0x2b, 0x57, 0x6a, 0xe9, 0x38, 0x61, 0x3d, 0xc1, 0xf9, 0xfe, 0x87, 0x34, 0x7d, 0x61,
	0x79, 0x58, 0xe4, 0xe5, 0xfa, 0xee, 0xb2, 0x4e, 0x6d, 0xea, 0x3f, 0x55, 0xd4, 0xd9, 0xfe, 0xb7,
	0xc1, 0xdb, 0xe2, 0xf5, 0xa6, 0xa7, 0xaa, 0x0f, 0xde, 0x54, 0x38, 0x0d, 0x61, 0x30, 0x58, 0x75,
	0xd8, 0xf8, 0xae, 0x49, 0x19, 0xdd, 0x62, 0x3e, 0xd0, 0xfd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1c, 0xc7, 0x58, 0xce, 0x3e, 0x01, 0x00, 0x00,
}
