// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/pagination.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaginationSortRequest struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction            string   `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationSortRequest) Reset()         { *m = PaginationSortRequest{} }
func (m *PaginationSortRequest) String() string { return proto.CompactTextString(m) }
func (*PaginationSortRequest) ProtoMessage()    {}
func (*PaginationSortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5862f1df5c23908, []int{0}
}

func (m *PaginationSortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationSortRequest.Unmarshal(m, b)
}
func (m *PaginationSortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationSortRequest.Marshal(b, m, deterministic)
}
func (m *PaginationSortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationSortRequest.Merge(m, src)
}
func (m *PaginationSortRequest) XXX_Size() int {
	return xxx_messageInfo_PaginationSortRequest.Size(m)
}
func (m *PaginationSortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationSortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationSortRequest proto.InternalMessageInfo

func (m *PaginationSortRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *PaginationSortRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type PaginationRequest struct {
	CurrentPage          int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	ItemPerPage          int32                  `protobuf:"varint,2,opt,name=item_per_page,json=itemPerPage,proto3" json:"item_per_page,omitempty"`
	Sort                 *PaginationSortRequest `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PaginationRequest) Reset()         { *m = PaginationRequest{} }
func (m *PaginationRequest) String() string { return proto.CompactTextString(m) }
func (*PaginationRequest) ProtoMessage()    {}
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5862f1df5c23908, []int{1}
}

func (m *PaginationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationRequest.Unmarshal(m, b)
}
func (m *PaginationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationRequest.Marshal(b, m, deterministic)
}
func (m *PaginationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationRequest.Merge(m, src)
}
func (m *PaginationRequest) XXX_Size() int {
	return xxx_messageInfo_PaginationRequest.Size(m)
}
func (m *PaginationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationRequest proto.InternalMessageInfo

func (m *PaginationRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *PaginationRequest) GetItemPerPage() int32 {
	if m != nil {
		return m.ItemPerPage
	}
	return 0
}

func (m *PaginationRequest) GetSort() *PaginationSortRequest {
	if m != nil {
		return m.Sort
	}
	return nil
}

type PaginationResponse struct {
	CurrentPage          int32    `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPageCount       int32    `protobuf:"varint,2,opt,name=total_page_count,json=totalPageCount,proto3" json:"total_page_count,omitempty"`
	ItemPerPage          int32    `protobuf:"varint,3,opt,name=item_per_page,json=itemPerPage,proto3" json:"item_per_page,omitempty"`
	TotalItemCount       int32    `protobuf:"varint,4,opt,name=total_item_count,json=totalItemCount,proto3" json:"total_item_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationResponse) Reset()         { *m = PaginationResponse{} }
func (m *PaginationResponse) String() string { return proto.CompactTextString(m) }
func (*PaginationResponse) ProtoMessage()    {}
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5862f1df5c23908, []int{2}
}

func (m *PaginationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationResponse.Unmarshal(m, b)
}
func (m *PaginationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationResponse.Marshal(b, m, deterministic)
}
func (m *PaginationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationResponse.Merge(m, src)
}
func (m *PaginationResponse) XXX_Size() int {
	return xxx_messageInfo_PaginationResponse.Size(m)
}
func (m *PaginationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationResponse proto.InternalMessageInfo

func (m *PaginationResponse) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *PaginationResponse) GetTotalPageCount() int32 {
	if m != nil {
		return m.TotalPageCount
	}
	return 0
}

func (m *PaginationResponse) GetItemPerPage() int32 {
	if m != nil {
		return m.ItemPerPage
	}
	return 0
}

func (m *PaginationResponse) GetTotalItemCount() int32 {
	if m != nil {
		return m.TotalItemCount
	}
	return 0
}

func init() {
	proto.RegisterType((*PaginationSortRequest)(nil), "common.PaginationSortRequest")
	proto.RegisterType((*PaginationRequest)(nil), "common.PaginationRequest")
	proto.RegisterType((*PaginationResponse)(nil), "common.PaginationResponse")
}

func init() { proto.RegisterFile("common/pagination.proto", fileDescriptor_e5862f1df5c23908) }

var fileDescriptor_e5862f1df5c23908 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4e, 0xac, 0x40,
	0x10, 0x85, 0xc3, 0xfc, 0x25, 0x53, 0x73, 0xaf, 0x51, 0xa2, 0x91, 0x85, 0x1a, 0x64, 0xc5, 0x06,
	0x88, 0xfa, 0x06, 0xba, 0x32, 0x6e, 0x08, 0xee, 0xdc, 0x10, 0xe8, 0x29, 0x09, 0xc9, 0xd0, 0xd5,
	0x16, 0xc5, 0x63, 0xf8, 0x2c, 0xbe, 0xa2, 0xa1, 0x7b, 0x9c, 0x99, 0x64, 0x5c, 0xb8, 0xec, 0x53,
	0x5f, 0xbe, 0x9c, 0x93, 0x86, 0x4b, 0x45, 0x5d, 0x47, 0x3a, 0x33, 0x55, 0xd3, 0xea, 0x4a, 0x5a,
	0xd2, 0xa9, 0x61, 0x12, 0xf2, 0x17, 0xee, 0x10, 0xbd, 0xc0, 0x45, 0xbe, 0xbb, 0xbd, 0x12, 0x4b,
	0x81, 0x1f, 0x03, 0xf6, 0xe2, 0x9f, 0xc3, 0xfc, 0xbd, 0xc5, 0xcd, 0x3a, 0xf0, 0x42, 0x2f, 0x5e,
	0x16, 0xee, 0xe1, 0x5f, 0xc1, 0x72, 0xdd, 0x32, 0xaa, 0x91, 0x0e, 0x26, 0xf6, 0xb2, 0x0f, 0xa2,
	0x4f, 0x0f, 0xce, 0xf6, 0xb6, 0x1f, 0xd3, 0x2d, 0xfc, 0x53, 0x03, 0x33, 0x6a, 0x29, 0x4d, 0xd5,
	0xa0, 0x15, 0xce, 0x8b, 0xd5, 0x36, 0xcb, 0xab, 0x06, 0xfd, 0x08, 0xfe, 0xb7, 0x82, 0x5d, 0x69,
	0x90, 0x1d, 0x33, 0x71, 0xcc, 0x18, 0xe6, 0xc8, 0x96, 0xb9, 0x83, 0x59, 0x4f, 0x2c, 0xc1, 0x34,
	0xf4, 0xe2, 0xd5, 0xfd, 0x75, 0xea, 0x06, 0xa4, 0xbf, 0xb6, 0x2f, 0x2c, 0x1a, 0x7d, 0x79, 0xe0,
	0x1f, 0xf6, 0xe9, 0x0d, 0xe9, 0x1e, 0xff, 0x52, 0x28, 0x86, 0x53, 0x21, 0xa9, 0x36, 0x16, 0x28,
	0x15, 0x0d, 0x5a, 0xb6, 0x9d, 0x4e, 0x6c, 0x3e, 0x42, 0x4f, 0x63, 0x7a, 0x5c, 0x7d, 0x7a, 0x5c,
	0x7d, 0x67, 0xb3, 0xa4, 0xb3, 0xcd, 0x0e, 0x6c, 0xcf, 0x82, 0x9d, 0xb5, 0x3d, 0x86, 0x6f, 0x37,
	0x0d, 0x25, 0x0d, 0x1b, 0x95, 0xe0, 0x38, 0x10, 0x59, 0x61, 0x52, 0x63, 0x66, 0xea, 0xcc, 0xed,
	0xad, 0x17, 0xf6, 0xff, 0x1e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x47, 0x0c, 0x03, 0xda,
	0x01, 0x00, 0x00,
}
